### ISSUE TITLE
On Standalone script closeBehavior: accept does not work 

### ISSUE THREAD

**Issue by niallzato** [segmentio/consent-manager#104]
**Issue**
For the standalone script the following does not work as expected:
https://github.com/segmentio/consent-manager#closebehavior
closeBehavior: 'accept'
 This behavior is a regression as it works in version 4.3.0 but no longer works in 5.0.0 
**Steps to reproduce**
Page with 5.0.0, note closing the banner does not accept consent
https://prigiattiperrut.github.io/consentmanager3.html

Page with 4.3.0, note closing the banner does accept consent
https://prigiattiperrut.github.io/consentmanager2.html

**Comment by notfelineit** [comment]
Thanks for reporting this! :-) We will prioritize this bug fix ASAP

**Comment by jalberto** [comment]
hi, @notfelineit is there any progress on this?

**Comment by grandmastermilo** [comment]
@niallzato still getting the issue on 4.3.0. any tips or other dependencies?

**Comment by blindman** [comment]
I ran into this issue using the React component and was able to solve it by using a passthrough function.

`closeBehavior={(categories) => categories}`

This sets all the preferences to `null` and properly sets the cookie as though all are accepted.

**Comment by Intrepidd** [comment]
This is still happening

**Comment by corydhmiller** [comment]
We also ran into this issue with 4.13.1 in the standalone version. We ended up passing @blindman's fix in the params:

```
container: "#target-container",
    writeKey: ...,
    shouldRequireConsent: inEU,
    bannerContent: bannerContent,
    bannerSubContent: bannerSubContent,
    preferencesDialogTitle: preferencesDialogTitle,
    preferencesDialogContent: preferencesDialogContent,
    cancelDialogTitle: cancelDialogTitle,
    cancelDialogContent: cancelDialogContent,
    closeBehavior: (categories) => {
      categories;
    },
 ```
