### ISSUE TITLE
Vue integration ?

### ISSUE THREAD

**Issue by jrpersico-spurred** [segmentio/consent-manager#106]
Hi, thank you for this plugin !

Are there any guides on how to integrate this with Vue?

Thanks !

**Comment by felipe-najson-ntf** [comment]
Hi @jrpersico-spurred, sorry for the late reply.

Consent Manager and ConsentManagerBuilder are based on React components, so it is not currently compatible with other frameworks such as Vue.js or Angular. In case you want to use it in other framework than React, you have to use Standalone implementation.
https://github.com/segmentio/consent-manager#standalone-script

I will be adding this note to the documentation to avoid future misunderstandings.

Segment team.
