### ISSUE TITLE
Consent manager shows "Segment" in dialog content

### ISSUE THREAD

**Issue by callmevlad** [segmentio/consent-manager#11]
When using the standard embed (and when looking at the [default Storybook example](https://segmentio.github.io/consent-manager/index.html?selectedKind=ConsentManager&selectedStory=Standalone%20React%20Component&full=0&addons=0&stories=1&panelRight=0)), the dialog content shows "Segment" in the copy:

![image](https://user-images.githubusercontent.com/785166/40566555-1caa1b58-6026-11e8-8dec-f41b408851f4.png)

Is this intentional? It seems like it should be "We" or something more generic, otherwise this doesn't seem usable for other companies. Or is there a way to override it?

**Comment by nettofarah** [comment]
Hey, @callmevlad 
Thanks for calling that out.

Yeah, that sounds like an oversight on our end 😅 
We can change the language the copy to say "We use browser cookies..."

**Comment by nettofarah** [comment]
@jfmaggie is on it :)

**Comment by callmevlad** [comment]
Thanks @nettofarah and @jfmaggie! 👏 I was [halfway to sending a pull request](https://github.com/callmevlad/consent-manager/commit/8d68a0b22f15ce6c99086646d018a9d57f7d9107), but sounds like you're ahead of me already 😄

**Comment by jfmaggie** [comment]
@callmevlad Thanks, feel free to submit the PR! 🙌

**Comment by jfmaggie** [comment]
Hey @callmevlad I fixed it in this one https://github.com/segmentio/consent-manager/pull/13

**Comment by Rowno** [comment]
🙈

**Comment by Rowno** [comment]
Fixed in [1.1.1](https://github.com/segmentio/consent-manager/releases/tag/v1.1.1)!

**Comment by callmevlad** [comment]
Thanks @Rowno!

Do you know how I can find out the new `integrity` hash for the new `https://unpkg.com/@segment/consent-manager@1.1.1/standalone/consent-manager.js` script?

Happy to update the doc examples as well if it helps 😃

**Comment by Rowno** [comment]
It's `cptjdzM9JCyAzOliNVMI+8U60l1MgdGbgop1MFfYoiU=`. You can get it by running `shasum -b -a 256 consent-manager.js | xxd -r -p | base64` on the file.

More info here: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#Using_Subresource_Integrity
