### ISSUE TITLE
openConsentManager button of standalone script enforces background color

### ISSUE THREAD

**Issue by ajascha** [segmentio/consent-manager#112]
Hi everyone, our marketing site runs on Webflow and we have embedded the button for opening the tracking settings. It appears that it comes with the same background color that has been specified for the banner, other styling options are not affected. Does anyone know how to deal with this?

https://www.loom.com/share/fe47ab9740f245d0b001e8c5f34ad090

**Comment by felipe-najson-ntf** [comment]
Hi @ajascha, sorry for the late reply.
I'm not sure which button you mean, but you can customize a button and set an event that when you click it, simply open the tracking settings as seen here.

![image](https://user-images.githubusercontent.com/89416739/134698355-041dc79c-d60a-4f8c-9213-718195fe2e7f.png)

On the other hand, I leave you the customizations that can be made to the santadalone version of the library. You can customize both the text color and the background color of the banner.
Here they are documented.
https://github.com/segmentio/consent-manager#bannertextcolor

Here is an example of customization of both the button to open the consent and the banner itself.
![Screen Shot 2021-09-24 at 12 05 10](https://user-images.githubusercontent.com/89416739/134698484-2a0f53e2-ffc7-46ba-9665-38f50aab5c46.png)

I also encourage you to review the storybooks to see the different use cases, I hope my answer is helpful.
Regards, Segment team.

**Comment by ajascha** [comment]
We are past that point by now but I'm probably not the last one to wonder 😄 Thanks Felipe!
