### ISSUE TITLE
ConsentManager with initialPreferences doesn't set the cookie

### ISSUE THREAD

**Issue by joker402** [segmentio/consent-manager#121]
I am using the ConsentManager react component and passing initialPreferences as follows in order to have the radio buttons prefilled on the "no" option: 
```
    initialPreferences={{
          advertising: false,
          functional: false,
          marketingAndAnalytics: false
    }}
```
When I don't change any of the radio button values and I click "save":
- (expected) the panel is closed and the cookies banner is hidden;
- (not expected) no cookie `tracking-preferences` is set. 
The next time the page is refreshed or the route changes, the banner is shown again.

Expected behaviour: when the radio buttons are preselected and the user does not change any value, saving should set the `tracking-preferences` cookie (with all options to "false").

Note: If I change one radio button value to "yes" and then back to "no" *before* saving, and then I save, the cookie is set properly.

**Comment by luistorres** [comment]
I'm facing the exact same issue, though I noticed that on segment website it behaves correctly. Are they using a different internal version of this component, or are the docs somehow incomplete?

**Comment by luistorres** [comment]
@joker402 downgraded to version 4.2.2 (which is the one used on segment website afaik) and it seems to work...though this is a bit weird as it doesn't show up on changelog.

**Comment by Dezzymei** [comment]
I have the same issue. It always seems to show, unless I hit no for one item.

**Comment by Dezzymei** [comment]
Even downgrading doesn't seem to solve my problem.

**Comment by Dezzymei** [comment]
I managed to fix this by adding this to the list of properties on ConsentManager: 

          closeBehavior={(categories) => categories}


as per https://github.com/segmentio/consent-manager/issues/104

This should probably be added by default?!
