### ISSUE TITLE
Accepting the consent is causing my site to refresh endlessly

### ISSUE THREAD

**Issue by nesbtesh** [segmentio/consent-manager#127]
Whenever you save the segment concept cookies the websites refreshes endlessly

**Comment by nesbtesh** [comment]
You can take a look here: https://staging.noritex.com/es/

**Comment by s-herbert** [comment]
I've just encountered this as well

**Comment by Dezzymei** [comment]
I think you need to make sure you comment out or remove the line:

```analytics.load('your_key');```

That was an issue for me but the documentation says you need to do this for it to work.

**Comment by kelcook** [comment]
We are seeing this same behavior on https://segment.build/designsystem/.

**Comment by felipe-najson-ntf** [comment]
Hi everyone! I adhere to what @Dezzymei says. Verify that you have remove that line in the script. In the current version of consent-manager no reload errors have been found. If anyone continues to have problems, feel free to open a new issue.

We will close this issue definitively, thank you for your contribution.
Segment Team.
