### ISSUE TITLE
Internationalization / Customizing the content of the consent manager

### ISSUE THREAD

**Issue by Intrepidd** [segmentio/consent-manager#137]
Hi,

The text within the consent manager seems to be hardcoded in english : 

https://github.com/segmentio/consent-manager/blob/e63972cb79142efda93dab8fc6e89d99a90af827/src/consent-manager/preference-dialog.tsx#L166-L170

Is there any plan to support internationalization or letting the user specify those strings in a drop-in manner without having to reimplement a react component ? 

Thanks

**Comment by felipe-najson-ntf** [comment]
Hi @Intrepidd, sorry for the late reply. Many people are asking for this feature so we will be working these weeks to make the consent table more customizable.

I will notify you when I have an update on this feature.

Regards, segment team
