### ISSUE TITLE
Consent banner trigger multiple times after tracking is accepted by user

### ISSUE THREAD

**Issue by roosterhack** [segmentio/consent-manager#139]
We are using consent manager in both our marketing site and our own application. If the user accepted tracking consent in the marketing site, in our application, the consent manager should not invoke to ask the user to consent tracking again. When the user accepted tracking in our application, she goes back to the marketing site, the consent banner invokes again even tho all tracking is already accepted by the user.

Expected behaviour:
The user only needs to accept the consent once either in the marketing or application site.

Here is an example of the settings of the component:
` <ConsentManager
          writeKey={segmentKey}
          closeBehavior={() => ({
            functional: true,
            advertising: true,
            marketingAndAnalytics: true,
          })}
          shouldRequireConsent={() => true}
          bannerContent={bannerContent}
          bannerSubContent={bannerSubContent}
          preferencesDialogTitle={preferencesDialogTitle}
          preferencesDialogContent={preferencesDialogContent}
          cancelDialogTitle={cancelDialogTitle}
          cancelDialogContent={cancelDialogContent}
          implyConsentOnInteraction={false}
          cdnHost="cdnsgmnt.domain.com"
        />`

**Comment by blackge** [comment]
+1

**Comment by felipe-najson-ntf** [comment]
Hi @roosterhack, sorry for the late reply. Does the problem still persist? If so, maybe you can give me more information about the context in which you use consent manager to help you.

For instance:
- What version do you use? Standalone script, Consent Manager or ConsentManagerBuilder only?
- What is your application and your marketing site built on? React, Vue.js, JavaScript only? 

Thanks, segment team.
