### ISSUE TITLE
Is the repo still maintained?

### ISSUE THREAD

**Issue by dmitry-zaets** [segmentio/consent-manager#141]
Looks like the repo hasn't been maintained for a while. Can you guys give away member permission to someone who can at least merge the dependency updates to fix the vulnerabilities?

**Comment by Dezzymei** [comment]
Seconded please

**Comment by santialbo** [comment]
Can we get an update from segment? @pooyaj 
@dmitry-zaets I've seen you forked the repo and made a few changes, have you published it on npm?

Is it worth start using this library as of today?

**Comment by dmitry-zaets** [comment]
> Can we get an update from segment? @pooyaj
> @dmitry-zaets I've seen you forked the repo and made a few changes, have you published it on npm?
> 
> Is it worth start using this library as of today?
> What alternatives are there?

Yes, we've posted it as https://www.npmjs.com/package/@boatim/consent-manager for now.
We are going to add an option to show the popup with an overlay, so it's more visible to the end-user.

**Comment by felipe-najson-ntf** [comment]
Hello everyone! I will be working during these time to solve all the repository issues and keep it updated.

Segment team.
