### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by adrianwix** [segmentio/consent-manager#158]
Please provide complete examples of usage with Nuxt, Vue, React, Next and Angular. I don't think it's in your interest for developers everyone to hate working with your product because of the bad DX. Thanks :D.

Let me do a quick example of good DX

```
yarn add @segment/vue-consent-manager // First we use a package manager because we are in the year 2021

and then for example in your Vue application you only import the component and use
import { ConsentManager } from '@segment/vue-consent-manager'
```

**Comment by felipe-najson-ntf** [comment]
Hi @adrianwix, sorry for the late reply.

Consent Manager and ConsentManagerBuilder are based on React components, so it is not currently compatible with other frameworks such as Vue.js or Angular. In case you want to use it in other framework than React, you have to use Standalone implementation.
https://github.com/segmentio/consent-manager#standalone-script

I will be adding this note to the documentation to avoid future misunderstandings, thanks for your contribution!
