### ISSUE TITLE
Broken link in read me on how to use consent manager

### ISSUE THREAD

**Issue by ferrucc-io** [segmentio/consent-manager#165]
```
The Segment Consent Manager can be used in several ways, depending on how custom you want your visitor's experience to be.

To get started, make sure you're using the latest version of the analytics.js snippet (4.1.0 or above) and remove the analytics.load("YOUR_WRITE_KEY"); call (so the consent manager can manage the loading process). Then continue onto one of the implementation methods below.
```

First thing: the link in the Readme to `analytics.js snippet` points to `https://segment.com/product/connections/sources/catalog/libraries/website/javascript/quickstart/#step-1-copy-the-snippet`  which is a broken link

Second it's not clear how to load the consent manager on a nextjs app like this one: https://github.com/vercel/next.js/tree/canary/examples/with-segment-analytics

```
import * as snippet from '@segment/snippet'
```

There is no analytics.load happening there!

Would be good if you included instructions to disable loading for the snippet like:

```
  renderSnippet() {
    const opts = {
      apiKey: API_KEY,
      // note: the page option only covers SSR tracking.
      // Page.js is used to track other events using `window.analytics.page()`
      page: true,
      load: false,
    }

    if (ENV === 'development') {
      return snippet.max(opts)
    }

    return snippet.min(opts)
  }
```

**Comment by felipe-najson-ntf** [comment]
Hello @ferrucc-io, thanks for advising. The link has already been fixed.
On the other hand, I will be working these days to add an example of how to use the library in a nextJS application.

Segment team.
