### ISSUE TITLE
Stand-alone script with default implementation from README produces undesired characters in consent manager [Â Ã Â]

### ISSUE THREAD

**Issue by dskvr** [segmentio/consent-manager#178]
Been trying to find the root cause of this for a while and I'm afraid I'm unable to find what's causing this. Using the example strait from the README without any modification other than the write key. 

<img width="1565" alt="Screenshot 2021-10-10 at 10 12 36" src="https://user-images.githubusercontent.com/299465/136687965-644fb2fa-16d6-490f-b62d-492c32bd1d5a.png">

JS Console is clean as well. 

Any ideas or suggestions?

**Comment by felipe-najson-ntf** [comment]
Hello @dskvr, a little update. Apparently the symbols Â Ã Â that appear are related to the character 'of the quotation mark. I just tested the standalone version and it works fine.
Perhaps your browser does not support the symbol or you have inadvertently made a change in the snippet when pasting it.

If the error could continue, you could change the default text from the bannerContent prop.
![image](https://user-images.githubusercontent.com/89416739/136980583-0f03cbc9-abb4-4453-bcc6-6cfca419c769.png)

Feel free to reply if you still can't fix it. 
Regards, segment team.
