### ISSUE TITLE
Error: event.isImmediatePropagationStopped is not a function

### ISSUE THREAD

**Issue by adpoyao** [segmentio/consent-manager#18]
I have an app that uses the standalone consent-manager script in index.html. The consent manager piece is working as expected along with the latest analytics scripts. However, in the same app I am have pre-existing codes using [video.js ](https://videojs.com/) for video frameworks, and having the consent-manager script causes this error to appear: 

` Uncaught TypeError: event.isImmediatePropagationStopped is not a function
    at data.dispatcher (video.js:22508)`

The block of code that is causing this to happen is:

```
<script
        src="https://unpkg.com/@segment/consent-manager@1.1.1/standalone/consent-manager.js"
        integrity="sha256-cptjdzM9JCyAzOliNVMI+8U60l1MgdGbgop1MFfYoiU="
        crossorigin="anonymous"
        defer
        data-container="#target-container"
        data-writeKey="<hidden>"
        data-bannerContent="We use cookies (and other similar technologies) to collect data to improve your experience on our site."
        data-preferencesDialogTitle="Website Data Collection Preferences"
        data-preferencesDialogContent="We use data collected by cookies and JavaScript libraries to improve your browsing experience, analyze site traffic, deliver personalized advertisements, and increase the overall performance of our site."
        data-cancelDialogTitle="Are you sure you want to cancel?"
        data-cancelDialogContent="Your preferences have not been saved. By continuing to use our website, you՚re agreeing to our Website Data Collection Policy."
        ></script>
```

I wasn't able to find codes in consent-manager implementation that could have causes this. Any help is appreciated, thanks.

**Comment by Rowno** [comment]
Thanks for trying out the consent manager!

I have no idea what could be causing it. 😅 Can you provide more details like the full stack trace, describe when the error happens (on load/click/scroll/etc) or even better provide a reduced test case?

**Comment by Josecc** [comment]
@adpoyao did you get this solved? I'm having the same issue with the brightcove player. It works as expected without including the consent manager, but when I include it, it breaks and doesn't play the video.

@Rowno the stack trace for mine is:
`index.js:25548 Uncaught TypeError: event.isImmediatePropagationStopped is not a function
    at HTMLDivElement.data.dispatcher (index.js:25548)
data.dispatcher @ index.js:25548`

The index.js file its looking at is http://players.brightcove.net/104524641001/default_default/index.js

**Comment by Josecc** [comment]
Turns out Brightcove uses video.js under the hood. [This is the line that is throwing the error](https://github.com/videojs/video.js/blob/ebf8d6671c056595423ca2b4ae75fe399cfdf3a3/src/js/utils/events.js#L288), which only happens when the segment consent manager script is included.

**Comment by Josecc** [comment]
@Rowno Also, here's a reduced test case:https://gist.github.com/Josecc/232e8f3e6e7b44e7c66f7c908ea62a91

I removed the segment analytics and configuration, but if you add those too, the same issue occurs. Whenever https://gist.github.com/Josecc/232e8f3e6e7b44e7c66f7c908ea62a91#file-index-html-L5-L9 is commented out or deleted, the video works (even if the configuration or segment analytics scripts remain).

**Comment by Rowno** [comment]
It seems there's a conflict between Inferno.js and Video.js, switching to React fixes the issue. Video.js is monkey patching all the native events so there's probably some sort of race condition happening: https://github.com/videojs/video.js/blob/ebf8d6671c056595423ca2b4ae75fe399cfdf3a3/src/js/utils/events.js#L160-L169

We're using Inferno.js in the standalone build to reduce the bundle size by 70kb.

If you have React setup on your site, the simple solution would be to mount the consent manager yourself using the React component: https://github.com/segmentio/consent-manager#consentmanager

Another solution is to create a custom build of the standalone consent manager that uses React instead of Inferno.js. To do that you just need to comment out these two lines and then run `yarn build`: https://github.com/segmentio/consent-manager/blob/8b6e13dcc37617aab14180b7315fac9ea1d91ae7/webpack.config.js#L16-L17

Otherwise I don't know how to fix this issue.

**Comment by Josecc** [comment]
Ahh **thank you** @Rowno ! We ended up following the custom build solution and it worked like a charm. Weird that inferno acts different than react, but I see why you kept it for the smaller size.

**Comment by Havunen** [comment]
I opened pull request https://github.com/segmentio/consent-manager/pull/30 to fix this issue.

**Comment by felipe-najson-ntf** [comment]
Hello everyone, a note before closing the issue. This was resolved by migrating to Preact (so we can get support for hooks).

Therefore, I will be closing this issue.
