### ISSUE TITLE
Errors for: "Cannot read properties of null (reading 'replaceChild')"

### ISSUE THREAD

**Issue by andreasmcdermott** [segmentio/consent-manager#189]
We are getting a lot of errors in Sentry with the following error message: `Cannot read properties of null (reading 'replaceChild')`

The stack trace is as follows:

```
TypeError: Cannot read properties of null (reading 'replaceChild')
  at replaceChild(./node_modules/inferno/dist/index.esm.js:372:1)
  at replaceWithNewNode(./node_modules/inferno/dist/index.esm.js:1382:1)
  at patch(./node_modules/inferno/dist/index.esm.js:1388:1)
  at updateClassComponent(./node_modules/inferno/dist/index.esm.js:1606:1)
  at applyState(./node_modules/inferno/dist/index.esm.js:2105:1)
  at queueStateChanges(./node_modules/inferno/dist/index.esm.js:2056:1)
  at setState(./node_modules/inferno/dist/index.esm.js:2158:1)
  at call(./src/consent-manager-builder/index.js:118:10)
```

I haven't been able to figure out why we are getting this error and I'm not able to reproduce it locally yet. Any idea of why this would happen?

**Comment by nd4p90x** [comment]
@felipe-najson-ntf Please take a look into this as soon as possible, thank you.

**Comment by felipe-najson-ntf** [comment]
Hello @andreasmcdermott this means that you are trying to read from an object that is not there. 
I would need more information to be able to reproduce the problem and help you.

- What implementation of consent manager do you use? Standalone, Consent Manager or ConsentManagerBuilder?
- In what framework or language are you using the library?
- If possible, upload the code snippet where you implement Consent Manager

Thank you very much, segment team.

**Comment by andreasmcdermott** [comment]
This is initialized in plain JS using the standalone version.

 This is our code that initializes segment and the consent-manager:

```js
export const identifyUser = async (user) => {
  await import(/* webpackChunkName: "segment" */ 'static/lib/segment');
  // loadScript creates a script tag and inserts it into the document.
  await Dom.Promises.loadScript('https://unpkg.com/@segment/consent-manager@1.1.2/standalone/consent-manager', {
    attributes: {
      integrity: 'sha256-N/iVJLiB/wdWBQrbxPZt5wj5N2d2wGDoqycQbkPOhGo=',
      crossorigin: 'anonymous',
      defer: true,
    },
  });
  try {
      window.analytics.identify(user.id, getUserParameters(user, paymentPlan));
  } catch (err) {
    Log.error(err);
  }
};
```

`static/lib/segment` looks like this:

```js
// begin segment snippet

!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(n,o);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
  analytics.page();
}}();

// end segment snippet

window.consentManagerConfig = function (exports) {
  var React = exports.React;
  var inEU = exports.inEU;

  return {
    container: '#consent-manager',
    writeKey: window.SEGMENT_API_KEY,
    otherWriteKeys: [...],
    shouldRequireConsent: inEU,
    bannerContent: ...,
    preferencesDialogTitle: ...,
    preferencesDialogContent: ...,
    cancelDialogTitle: ...,
    cancelDialogContent: ...,
    implyConsentOnInteraction: false
  };
};
```

**Comment by andreasmcdermott** [comment]
I have looked at this a bit more, and I've been able to reproduce it. It seems like it happens when a user has a active session, and we redirect them to a signed in page. Something like this:

* User goes to page A
* We run JS that checks if user is signed in
* If user is signed in, we redirect them to page B
* When redirect happens, the error mentioned above is printed to console.

**Comment by felipe-najson-ntf** [comment]
Hello again Andrea, thank you for your information.

I have reproduced the case and it seems that the problem is in the identifyUser () function. Every time you call that function you are loading the script and it is not the expected behavior.

In my case what I did was just add the script to the index.html
![image](https://user-images.githubusercontent.com/89416739/142203555-3abcd4b4-6a60-41ce-b3d1-1f98d42078a2.png)
![image](https://user-images.githubusercontent.com/89416739/142203815-fd70ee53-ae7b-4405-8035-b3a549ca435e.png)

Once this is done, you don't have to load script again in the identifyUser() function and you can do something like this.
![image](https://user-images.githubusercontent.com/89416739/142204231-57a75fa5-af3c-4a26-b3fe-1c9ef3298f43.png)

Let me know what you think and I hope it helps you!

Greetings, segment team.

**Comment by andreasmcdermott** [comment]
Thank you for getting back to me! 

Could you help me understand what is the root cause and if there is a way for us to avoid the issue without major changes to how we import the scripts? I wasn't at the company when this was written, but my understanding from talking to people that was, is that we want to lazily import the dependency to improve page load times. 

Our application is a "SPA", and `identifyUser` is only called once during app initialization, meaning it happens on the redirect when user is signed in (mentioned above), or if user manually refreshes the page, etc. But otherwise it shouldn't happen multiple times for the same user. However, I can add a check to ensure we don't download multiple times like this if that would help:

```
export const identifyUser = async (user) => {
  if (!window.analytics) {
    await import(/* webpackChunkName: "segment" */ 'static/lib/segment');
    await Dom.Promises.loadScript('.../consent-manager', {...});
  }
  try {
      window.analytics.identify(user.id, getUserParameters(user, paymentPlan));
  } catch (err) {
    Log.error(err);
  }
};
```

**Comment by nd4p90x** [comment]
@andreasmcdermott if this is still an issue for you, please feel free to re-open.  Thank you
