### ISSUE TITLE
How to access Consent info

### ISSUE THREAD

**Issue by BrunoBoehm** [segmentio/consent-manager#19]
Hi Segment, again great work on this banner I'm using it for most sites I'm currently working on and it works like a charm!

How do you recommend to access the consent information for each user ? i.e. when a client is asked to erase the consent for someone how should we go about accessing and erasing this information ? CookieBot for instance offers an interface to list, edit and delete consent.

Cheers, Bruno

**Comment by felipe-najson-ntf** [comment]
Hi @BrunoBoehm, sorry for the late reply. Once you accept the consent, the banner does not appear anymore. 
Therefore if a client want to delete the cookies the only way is manually from the browser console.

Maybe it can be a good feature for the future, but for now we are not considering it. Thanks for your contribution!

On the other hand I will be closing this issue. Segment team
