### ISSUE TITLE
preferencesDialogTemplate won't replace default value

### ISSUE THREAD

**Issue by davidvenin** [segmentio/consent-manager#190]
I am currently trying to replace default values for `preferencesDialogTemplate` following the doc : 

- I copy paste the default one 
- Here is the new :

```js
const dialogPreference = {
    headings: {
      allowValue: "Autoriser",
      categoryValue: "Categorie",
      purposeValue: "But",
      toolsValue: "Outils",
    },
    checkboxes: {
      noValue: "Non",
      yesValue: "Oui",
    },
    actionButtons: {
      cancelValue: "Annuler",
      saveValue: "Sauvegarder",
    },
    cancelDialogButtons: {
      cancelValue: "Oui, Annuler",
      backValue: "Retour",
    },
    categories: [
      {
        key: "functionnal",
        name: t("cookie-consent-functional-title"),
        description: t("cookie-consent-functional-content"),
      },
      {
        key: "marketing",
        name: t("cookie-consent-market-title"),
        description: t("cookie-consent-market-content"),
      },
      {
        key: "advertising",
        name: t("cookie-consent-publicity-title"),
        description: t("cookie-consent-publicity-content"),
      },
      {
        key: "essential",
        name: t("cookie-consent-functional-title"),
        description: t("cookie-consent-functional-content"),
      },
    ],
  };
```
<img width="748" alt="Capture d’écran 2021-11-15 à 16 57 14" src="https://user-images.githubusercontent.com/3694824/141813274-d9d4f175-b3c9-4fd9-a2ba-a823a5c5ec16.png">

As you can see, nothing happen for anything.

### Stack : 
```
"next": "^12.0.2",
"@segment/consent-manager": "^5.1.0",
```

Any thoughts ?

**Comment by felipe-najson-ntf** [comment]
Hi @davidvenin, DialogTemplate preference is not enabled in the current version.

For this to be available, we have to release a version of Consent Manager with the new features. I'm waiting for you to approve the pr #184 which is necessary to publish this new version.
Sorry for the delay. Please be patient, in these days we will publish this new version.

Greetings, Segment team.

**Comment by nd4p90x** [comment]
Version 5.4.0 closes this issue, thank you

**Comment by davidvenin** [comment]
Thank you for the release. Perfect for me.

**Comment by bencehusi** [comment]
Using https://unpkg.com/@segment/consent-manager@5.3.0/standalone/consent-manager.js I still can't get the default values to override.
