### ISSUE TITLE
Tool-based consent system

### ISSUE THREAD

**Issue by LionelPaulus** [segmentio/consent-manager#194]
Hi,

Using the standalone implementation, how can I have a tool-based consent system instead of the current category-based one?

Desired result:
![image](https://user-images.githubusercontent.com/789782/143280829-466628cd-4d6e-4259-9713-d4251588b49c.png)

Thanks!

**Comment by pooyaj** [comment]
hey @LionelPaulus, there are few examples of tool based implementation in the storybook. You can check out here: https://github.com/segmentio/consent-manager/blob/master/stories/3-tool-based.stories.tsx

**Comment by LionelPaulus** [comment]
These are examples using the React implementation but my question is about the standalone implementation.
Is it possible to achieve the same result?

**Comment by pooyaj** [comment]
Oh, I see. No unfortunately the standalone implementation uses category based consent. The only option is to use `ConsentManagerBuilder` and do a DIY UI layer.
