### ISSUE TITLE
What does context.consent actually do?

### ISSUE THREAD

**Issue by thomasboyt** [segmentio/consent-manager#198]
One of the things this library does is add a field to `track` calls indicating destinations that have been consented to. From the readme:

```
{
  "context": {
    "campaign": {},
    "consent": {
      "categoryPreferences": {
        "Amplitude": true,
        "Customer.io": true,
        "Google Analytics": true,
        "Webhooks": true
      },
      "defaultDestinationBehavior": "disable",
      "destinationPreferences": {
        "Amplitude": true,
        "Customer.io": true,
        "Google Analytics": true,
        "Webhooks": true
      }
    }
  },
  "event": "Send Track Event Clicked",
  "integrations": {
    "All": false,
    "Amplitude": true,
    "HubSpot": false,
    "Salesforce": false,
    "Segment.io": true
  }
}
```

However, I can find no documentation of this `consent` field in Segment - it's not part of the [Common Fields](https://segment.com/docs/connections/spec/common/) or [Track](https://segment.com/docs/connections/spec/track/) docs.

I assume that, if a destination is not consented to, the tracked event is not sent to it. However, I can't tell if this is guaranteed by this `consent` field. Separately, I know non-consented destinations don't have their SDKs loaded, which prevents events from being tracked, but I assume that for server-side destinations it would have to be enforced by Segment filtering the events. If this is implemented through `context.consent`, should that be documented somewhere?

Additionally, I do not understand the difference between the `categoryPreferences` and `destinationPreferences` fields as illustrated in this example. Would one take precedence over the other? Are both required?

**Comment by pooyaj** [comment]
@thomasboyt The `consent` object in the `context` doesn't have any impact on the delivery of the message (or any effect on how the payload is processed by Segment). It is just to add additional context to the event. The delivery is controlled via the `integrations` object in the payload.
