### ISSUE TITLE
Consider removing All: false from default integrations config

### ISSUE THREAD

**Issue by pietvanzoen** [segmentio/consent-manager#199]
I've discovered a bug where segment will prevent events being sent to a destination in some circumstances when `All` is `false` and the destination uses an object configuration rather than a boolean.

I'm not 100% sure where the bug lives, perhaps analytics.js or perhaps in segment's backend. But considering that consent-manager explicitly sets `integrations` config for each integration `All: false` is a little redundant. 

https://github.com/segmentio/consent-manager/blob/5db5e01915c03af9a791416ab8734829a2d0e52a/src/consent-manager-builder/analytics.ts#L44

**Comment by emont01** [comment]
@pietvanzoen can you describe the issue in detail? Why do you think that changing that setting will resolve the problem?

**Comment by nd4p90x** [comment]
@pietvanzoen we would be happy to work with you on this issue if you decide it is still applicable, feel free to re-open or start a new thread.  Thank you.
