### ISSUE TITLE
wd.analytics.addSourceMiddleware is not a function

### ISSUE THREAD

**Issue by JoaoPLGomes** [segmentio/consent-manager#203]
Currently trying to use ConsentManagerBuilder in a Next.js app but I got this error:

![image](https://user-images.githubusercontent.com/8902221/150963332-65416c51-0cfb-4052-8592-934b6bd98c09.png)

This is my _document file where I have the script: 

![image](https://user-images.githubusercontent.com/8902221/150964029-b40a32ab-c391-42f5-b33f-ba4f97177e32.png)

This is where I have the ConsentManagerBuilder with my UI : 

![image](https://user-images.githubusercontent.com/8902221/150964190-6b4e2949-2a13-4ccc-8e2b-b658b7beb05c.png)

I've tried different things but always got stuck with an error

**Comment by pooyaj** [comment]
This is probably due to an outdated Segment Snippet. Feel free to re-open if still seeing the issue after using latest snippet
