### ISSUE TITLE
How to add a custom category to consent manager without overriding existing categories?

### ISSUE THREAD

**Issue by collinwu** [segmentio/consent-manager#204]
I'm referencing Segment's article here about CCPA: https://segment.com/blog/segment-ccpa/

And in this image specifically, this is exactly what I'd like to reproduce, but given the documentation and trial and error behavior, I'm not entirely sure how this can be done without really digging into the library's source code and trying to understand it.

Essentially declaring a `customCategories` seems to override the default `Functional`, `Marketing & Analytics`, `Advertising` categories. 

I even tried adding this custom `Do Not Sell` category to the `preferencesDialogTemplate` and it doesn't work (Do Not Sell does not show up, but the existing categories do). Could Segment please advise? I was hoping this could be achieved easily by having `customCategories` extend existing `categories`, but it doesn't look like that's the default behavior.

![asset_pC3xIc7wjknM9E74](https://user-images.githubusercontent.com/6867357/151285507-d03bfcc5-76dc-4f86-8017-4ef7cbc6bb54.png)

```ts
function SegmentConsentManager() {
  const writeKey="abcdefg";
  const bannerSubContent = "UPDATE YOUR PREFERENCES";
  const preferencesDialogTitle = "Website Data Collection Preferences";
  const preferencesDialogContent =
    "We use data collected by cookies and JavaScript libraries to improve your browsing experience, analyze site traffic, deliver personalized advertisements, and increase the overall performance of our site.";
  const cancelDialogTitle = "Are you sure you want to cancel?";
  const cancelDialogContent =
    "Your preferences have not been saved. By continuing to use our website, you՚re agreeing to our Privacy Policy.";

  const customCategories = {
    "Do Not Sell": {
      purpose: "To prevent sale of data to third party tools",
      integrations: ["Google Analytics", "Amplitude"],
    },
  };

  const initialCategories = {
    functional: true,
    marketingAndAnalytics: true,
    advertising: true,
  };

  return (
      <ConsentManager
        writeKey={writeKey}
        initialPreferences={initialCategories}
        bannerContent={bannerContent}
        bannerSubContent={bannerSubContent}
        preferencesDialogTitle={preferencesDialogTitle}
        preferencesDialogContent={preferencesDialogContent}
        cancelDialogTitle={cancelDialogTitle}
        cancelDialogContent={cancelDialogContent}
        closeBehavior="accept"
        customCategories={customCategories}
        bannerBackgroundColor="#000"
        bannerTextColor="#fff"
      />
  );
}
```

**The result is this:**

<img width="754" alt="Screen Shot 2022-01-26 at 7 21 58 PM" src="https://user-images.githubusercontent.com/6867357/151286343-6e7a9150-58d6-4773-a704-339035ab4a97.png">

**Comment by tawe-segment** [comment]
This seems to be working by design. PR here to add usage note for the `customCategories` object:
https://github.com/segmentio/consent-manager/pull/208
