### ISSUE TITLE
Support event batching

### ISSUE THREAD

**Issue by amedee-os** [segmentio/consent-manager#209]
Hi,
Before using consent-manager, we used to enable analytic.js's [batching](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#batching) functionality by calling analytics.load() like this:

```
analytics.load("<write_key>", {
    integrations: {
      "Segment.io": {
        deliveryStrategy: {
          strategy: "batching",
          config: {
            size: 10,
            timeout: 5000
          }
        }
      }
    }
  });
```

Now that ConsentManagerBuilder is calling `load` for us, it doesn't look like there is a way to inject this config, since`conditionallyLoadAnalytics()` doesn't support setting anything but boolean values to the `integrations` object.

Could this be supported, perhaps by adding a `customIntegrations` prop that adds/overwrites values in the `integrations` object? Or a more narrow `SegmentIntegrationConfig` prop that would only set the `Segment.io` entry in the object? I can submit a PR as well.

**Comment by emont01** [comment]
@amedee-os please do submit your PR

**Comment by nd4p90x** [comment]
@amedee-os please feel free to submit a PR for this issue as you have stated.  I will re-open attach this issue once that has been completed.  Thank you!
