### ISSUE TITLE
Gatsby not show banner

### ISSUE THREAD

**Issue by ferrero1987** [segmentio/consent-manager#218]
Hi, 
When using gatsby, the blue banner doesn’t show up
![Schermata 2022-04-08 alle 15 17 27](https://user-images.githubusercontent.com/83806203/162443759-7e4d0dff-5c1c-4e2c-a3ab-62d2fe173b3a.png)

The code is here: https://codesandbox.io/s/kmvzm?file=/src/components/layout.js:2212-2613

**Comment by maurocanuto** [comment]
+1

**Comment by edsonjab** [comment]
Hi @ferrero1987 @maurocanuto,
We still work on that issue but for the moment you can add the attribute "otherWriteKeys" that would help to show the banner

![gatsbyError](https://user-images.githubusercontent.com/22898327/165154742-9344c103-a5a7-40d3-a034-17e2aad84e07.png)

**Comment by maurocanuto** [comment]
@edsonjab thanks for the help. What is the value to use for the `otherWriteKeys`? Is that another `Write Key` that we need to generate or the `Source ID`?

**Comment by nd4p90x** [comment]
@maurocanuto This is a secondary write key for another segment instance.  We found an issue where if this field is missing, the banner doesn't display properly with Gatsby.  We are currently working on a solution and will update the issue soon.

**Comment by maurocanuto** [comment]
@edsonjab Thanks! By adding a destination seems to be working now!
