### ISSUE TITLE
Dynamic integrations list

### ISSUE THREAD

**Issue by trefasp** [segmentio/consent-manager#225]
I am using the Consent Manager component where I need to pass custom categories as a prop. Is it a way to avoid writing that integrations of strings list in as a free text and to pass there directly what I receive as a response from getting integrations list request?
  const customCategories = {
    'Performance and Analytics': {
      **integrations: ['Google Analytics','Amplitude''],**
    },
  };

On each modification that is made on segment integrations list I have to rewrite again that custom categories

**Comment by edsonjab** [comment]
Hi @trefasp I suggest that you use a Global variable with that values, because that value is optional for Consent Manager and Consent Manager only handle the values when you specify that property

**Comment by trefasp** [comment]
Sorry, but is not clear for me. I need to define a custom category and there to pass via integrations list props the response that comes from fetch destination list.  It's true that I can let by default marketingAndAnalytics category, but there I need a custom description and a custom name

**Comment by trefasp** [comment]
Or maybe is it a way to use just a part of by default categories, for example to use just essential and marketing, not advertising and not functional

**Comment by edsonjab** [comment]
Hi @trefasp  I'm sorry, now I understand, the only way to define your own categories is using the property customCategories, if you will use the integrations list like categories, I suggest that you get that list before that you will render the ConsentManager component to build the customCategories property and to pass that property in the component.

**Comment by nd4p90x** [comment]
@trefasp Feel free to re-open if necessary.  Thank you
