### ISSUE TITLE
When will the pull requests be published on npm?

### ISSUE THREAD

**Issue by lapa182** [segmentio/consent-manager#229]
Hello! I saw a few pull requests (including mine) merged, but I can't see the newest version on NPM? Is there another way for us to consume the latest versions on NPM?

**Comment by brettdewoody** [comment]
You can install direct from Github to get the latest version. 

`npm install segmentio/consent-manager#master`

**Comment by lapa182** [comment]
@nd4p90x I can see the pull request was merged (🎉) but it's still not in NPM? 🤔

**Comment by nd4p90x** [comment]
@lapa182 the request for NPM has been sent, hopefully it is completed today or tomorrow.  Thanks

**Comment by nd4p90x** [comment]
@lapa182 @thekip @brettdewoody Sorry for the delay https://www.npmjs.com/package/@segment/consent-manager
