### ISSUE TITLE
`openConsentManager` doesn’t open ConsentManager

### ISSUE THREAD

**Issue by gryzzly** [segmentio/consent-manager#23]
Hey! Thanks for the useful tool! 

I think I am missing something, but `openConsentManager` doesn’t cause `ConsentManager` to show up. Also looking in the source of the function, it emits `openDialog` but there is nothing that handles that event, if I’m seeing this correctly.

Thanks!

**Comment by Rowno** [comment]
Not sure what to say, we're using `openConsentManager` in a bunch of places and it works fine. 😅 

The event is handled here though: https://github.com/segmentio/consent-manager/blob/5d253e08013e5662eac4243615de8b9e28f0c85c/src/consent-manager/container.js#L117

**Comment by gryzzly** [comment]
Thanks.

Not sure how I managed to miss it, as I tried `ack` on node_modules looking for `openDialog` and used Github’s search on the repo as well!

My issue had to do with the fact that `openConsentManager` was called before the component got mounted.
