### ISSUE TITLE
Supporting React v17 as a peer dependency

### ISSUE THREAD

**Issue by brettdewoody** [segmentio/consent-manager#230]
I appreciate all the recent updates! We had looked at using the Segment Consent Manager previously but it was incompatible with other deps we had, like React v17.

I see now the peer deps have been updated to React v18, and entirely skipped v17. Does it specifically need React v18, or could we add React v17 as a peer dep option?

**Comment by edsonjab** [comment]
HI @brettdewoody, do you need use the React 17 for a specific functionality? 

we upgrade to v18 because is recently and has many the improvements on the framework

**Comment by brettdewoody** [comment]
Updating to React 18 is possible, but I believe it will require us to update additional deps.

**Comment by nd4p90x** [comment]
There is a new branch that supports react v17.  We have yet to make and official release with this branch, but feel free to source from the new branch for your project.
https://github.com/segmentio/consent-manager/tree/react_v17
