### ISSUE TITLE
Create separate production build for consent-manager-builder? 

### ISSUE THREAD

**Issue by damassi** [segmentio/consent-manager#231]
Right now we're using the builder so that we can provide our own UI; however, looking at our bundle it appears as though `emotion` and so on is being included unnecessarily. It would be nice if we could import the builder directly and skip all of the other dependencies. 

Something like this:

```tsx
import ConsentManagerBuilder from '@segment/consent-manager/dist/consent-manager-builder'
```

Thoughts? Happy to contribute a PR if this ask is reasonable.

**Comment by edsonjab** [comment]
Hi @damassi  sure, you can make the PR and we can check your solution

**Comment by damassi** [comment]
Cool, will do 👍

**Comment by damassi** [comment]
Actually, digging deeper, this is already setup correctly! 

```tsx
import ConsentManagerBuilder from "@segment/consent-manager/commonjs/consent-manager-builder"
```

Going to close. Thanks for the very useful library.
