### ISSUE TITLE
Lodash loading issue

### ISSUE THREAD

**Issue by BodySplash** [segmentio/consent-manager#238]
Hi there,

If I bump consent manager to version 5.5.0, then my nextjs app (v 12.1.5) fails to compile:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module [...]/node_modules/lodash-es/lodash.js from [...]/node_modules/@segment/consent-manager/commonjs/consent-manager-builder/fetch-destinations.js not supported.
Instead change the require of lodash.js in [...]/node_modules/@segment/consent-manager/commonjs/consent-manager-builder/fetch-destinations.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> ([...]/node_modules/@segment/consent-manager/commonjs/consent-manager-builder/fetch-destinations.js:43:19)
```

I guess this is related to #234 but I must admit I'm not sure to understand why.

**Comment by Kudder1** [comment]
Same for me, although I'm using 

- consent manager 5.4.0
- nextjs 12.1.0

**Comment by mahowa** [comment]
is there a planned fix for this? what version was working before this update?

**Comment by nd4p90x** [comment]
The status under projects shows in progress.  We are currently working on a PR for this issue.  Thank you.

**Comment by mahowa** [comment]
I am still seeing this issue in the newest release. I also dont actually see any code changes in the PR linked here?

**Comment by edsonjab** [comment]
@mahowa are you still use nextjs 11.1.2?

**Comment by alexbchr** [comment]
I have the exact same issue on 5.6.0... Using Next.js version 12.2.2

**Comment by edsonjab** [comment]
Hi all, looks like is a problem with nextjs and lodash-es

https://github.com/vercel/next.js/issues/9607

I'm still work on found a solution because with other frameworks consent-manager works

**Comment by arijit-tweb** [comment]
> is there a planned fix for this? what version was working before this update?
> 
> consent manager 5.x.0 (all of these seem to have the same issue) nextjs 11.1.2

is previous versions really have this issue? did you try it?

**Comment by edsonjab** [comment]
Hi, we still work on how to solve this issue, but looks like is an with NextJS
[Here](https://www.freecodecamp.org/news/how-to-bypass-es-modules-error-in-next-js/) is an article with some explanation about that.

**Comment by BodySplash** [comment]
I've dig a little bit. 
It's not entirely a next issue. Indeed, the commonjs version of consent-manager is not valid, as it requires an es only module (lodash-es). 
I would be happy to find a way to tell next to use the esm version, but in the mean time, that doesn't address the fact that the cjs version shouldn't require lodash-es

**Comment by gat-developer** [comment]
> It's not entirely a next issue. Indeed, the commonjs version of consent-manager is not valid, as it requires an es only module (lodash-es).

This also affects the jest tests. Jest doesn't transpile node_modules by default. After bumping the newest version of `consent-manager` `jest` complains that it cannot parse lodash es file included by `consent-manager`

```
Details:

    /<my_app_path>/node_modules/lodash-es/lodash.js:10
    export { default as add } from './add.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1723:14)
      at Object.<anonymous> (node_modules/@segment/consent-manager/src/consent-manager-builder/fetch-destinations.ts:2:1)
```

There is of course a workaround (tell jest to transpile `lodash-es`), but I don't want jest to transpile lodash (which is not so small) for tests (that affects the tests execution time).

Maybe you have some suggestions?

**Comment by shortcircuit3** [comment]
Still needing a fix for this
