### ISSUE TITLE
how to use "openConsentManager()" method on standalone script?

### ISSUE THREAD

**Issue by arijit-tweb** [segmentio/consent-manager#239]
currently i'm getting consentManager: undefined in window object on my chrome browser.

> consentManager: undefined
consentManagerConfig: ƒ (exports)
length: 1
name: ""
prototype: {constructor: ƒ}
arguments: (...)
caller: (...)
[[FunctionLocation]]: index.js:418
[[Prototype]]: ƒ ()
[[Scopes]]: Scopes[4]

**Comment by arijit-tweb** [comment]
How to solve this? can you pls tell

**Comment by arijit-tweb** [comment]
> How to solve this? can you pls tell



> Hi @arijit-tweb that happens when the app did not have the script on header HTML
> 
> you can check this example on NextJS
> 
> https://github.com/segmentio/consent-manager#example-in-nextjs
> 
> like the section <script> ![image](https://user-images.githubusercontent.com/22898327/177579725-8fc944df-b4e4-4d43-8642-732242cf6cb0.png)
How to solve this? can you pls tell

**Comment by edsonjab** [comment]
@arijit-tweb you need add that script on your project, with that line recognize the consentManager into window object.
