### ISSUE TITLE
Partially blocks my screen

### ISSUE THREAD

**Issue by jhabdas** [segmentio/consent-manager#24]
Been seeing a lot of this lately. These should be geofenced or every client in the EU, or the EU should be sending a flag indicating they're in the EU so the rest of us don't suffer from GDPR popovers.

**Comment by Rowno** [comment]
You easily can using the [@segment/in-eu](https://github.com/segmentio/in-eu) package and the [`shouldRequireConsent`](https://github.com/segmentio/consent-manager#shouldrequireconsent) option, as shown in this example: https://github.com/segmentio/consent-manager#callback-function
