### ISSUE TITLE
Can We Enable For All Regions?

### ISSUE THREAD

**Issue by michaelgutierrez0** [segmentio/consent-manager#240]
Hi,
My company would like to use this consent manager but we would like to use it for all users. Even if they are not in the EU we would like to ask for consent. Do you know how this can be achieved? I see this package:
https://github.com/segmentio/in-eu
Is used to discover if they are in the EU. Could we overwrite this to always return true? 

Thank you for any help!

**Comment by michaelgutierrez0** [comment]
I was able to do this with:
shouldRequireConsent={() => true}

**Comment by nd4p90x** [comment]
@michaelgutierrez0 apologies for not getting back to you sooner.  
Were you able to find that in the documentation, or is that something we need to be more clear about?  
Glad you figured that out.  Let us know if you have any other issues.

**Comment by stereojones** [comment]
We're looking to do this too. Where would I set shouldRequireConsent to true with the Standalone Script? I tried doing the following, but get an error and nothing populates the `<div id="target-container">` . Any help is appreciated! I was hopeful after I found this question, but am not sure where to implement @michaelgutierrez0's solution or if it is possible with the Standalone script. I can tell by its formatting that it wouldn't likely go in the script as-is, but again am not sure. Thanks in advance for any advice!

`<script>
  window.consentManagerConfig = function(exports) {
    var React = exports.React
    var inEU = exports.inEU

    var bannerContent = React.createElement(
      'span',
      null,
      'We use cookies (and other similar technologies) to collect data to improve your experience on our site. By using our website, you՚re agreeing to the collection of data as described in our',
      ' ',
      React.createElement(
        'a',
        { href: 'https://amelia-aesthetics.webflow.io/privacy', target: '_blank' },
        'Website Data Collection Policy'
      ),
      '.'
    )
    var bannerSubContent = 'You can change your preferences at any time.'
    var preferencesDialogTitle = 'Website Data Collection Preferences'
    var preferencesDialogContent =
      'We use data collected by cookies and JavaScript libraries to improve your browsing experience, analyze site traffic, deliver personalized advertisements, and increase the overall performance of our site.'
    var cancelDialogTitle = 'Are you sure you want to cancel?'
    var cancelDialogContent =
      'Your preferences have not been saved. By continuing to use our website, you՚re agreeing to our Website Data Collection Policy.'

    return {
      container: '#target-container',
      writeKey: 'N4unUkonRPSao2evlN66FPEfbAVcOUY8',
      shouldRequireConsent: true,
      bannerContent: bannerContent,
      bannerSubContent: bannerSubContent,
      preferencesDialogTitle: preferencesDialogTitle,
      preferencesDialogContent: preferencesDialogContent,
      cancelDialogTitle: cancelDialogTitle,
      cancelDialogContent: cancelDialogContent
    }
  }
</script>`

**Comment by stereojones** [comment]
We're looking to do this too. Where would I set shouldRequireConsent to true with the Standalone Script? I tried doing the following, but get an error and nothing populates the <div id="target-container"> . Any help is appreciated! I was hopeful after I found this question, but am not sure where to implement @michaelgutierrez0's solution or if it is possible with the Standalone script. I can tell by its formatting that it wouldn't likely go in the script as-is, but again am not sure. Thanks in advance for any advice!

```<script>
  window.consentManagerConfig = function(exports) {
    var React = exports.React
    var inEU = exports.inEU

    var bannerContent = React.createElement(
      'span',
      null,
      'We use cookies (and other similar technologies) to collect data to improve your experience on our site. By using our website, you՚re agreeing to the collection of data as described in our',
      ' ',
      React.createElement(
        'a',
        { href: 'https://amelia-aesthetics.webflow.io/privacy', target: '_blank' },
        'Website Data Collection Policy'
      ),
      '.'
    )
    var bannerSubContent = 'You can change your preferences at any time.'
    var preferencesDialogTitle = 'Website Data Collection Preferences'
    var preferencesDialogContent =
      'We use data collected by cookies and JavaScript libraries to improve your browsing experience, analyze site traffic, deliver personalized advertisements, and increase the overall performance of our site.'
    var cancelDialogTitle = 'Are you sure you want to cancel?'
    var cancelDialogContent =
      'Your preferences have not been saved. By continuing to use our website, you՚re agreeing to our Website Data Collection Policy.'

    return {
      container: '#target-container',
      writeKey: 'WRITE-KEY',
      shouldRequireConsent: true,
      bannerContent: bannerContent,
      bannerSubContent: bannerSubContent,
      preferencesDialogTitle: preferencesDialogTitle,
      preferencesDialogContent: preferencesDialogContent,
      cancelDialogTitle: cancelDialogTitle,
      cancelDialogContent: cancelDialogContent
    }
  }
</script>```
