### ISSUE TITLE
How to overwrite `analytics.identify` call properties in `savePreferences`

### ISSUE THREAD

**Issue by mfrazie2** [segmentio/consent-manager#243]
How can I set the `context` with an IP address at this [call site](https://github.com/segmentio/consent-manager/blob/370a4b97116d75fbe71692d4e26d70d00222231f/src/consent-manager-builder/preferences.ts#L59)? When loading the Analytics library I currently use `analytics.page(null, null, {}, {context: {ip: '0.0.0.0'}});` to prevent IP address from being recorded. Is there a similar means to do this in the Consent Manager?

Issue #29 raised a similar question and was closed without comment. Given the last comment from a Segment maintainer was 2.5 years ago, I thought it would better to open a new issue.

**Comment by pooyaj** [comment]
@mfrazie2 would using a source middleware ( https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/middleware/ ) solve this issue?
