### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by lifeforced** [segmentio/consent-manager#246]
I noticed the last release on npmjs was from 2018? Is there a new version somewhere else we're supposed to be using today?

**Comment by jeffnappi** [comment]
Last release was [3 days ago](https://www.npmjs.com/package/@segment/consent-manager/v/5.6.0), however it seems they have not been tagging the releases in the git repo.

**Comment by nd4p90x** [comment]
@lifeforced https://www.npmjs.com/package/@segment/consent-manager/v/5.6.0
@jeffnappi git repo release version updated 

thank you
