### ISSUE TITLE
Set destinationPreferences with standalone script

### ISSUE THREAD

**Issue by mischasigtermans** [segmentio/consent-manager#247]
Hi there,

I want to disable a specific destination for our marketing website where we use the consent manager. We use the same write key on our app, with the same destinations, but without the consent manager (since the user is logged in and gave consent already with their sign up).

How can I set the `destinationPreferences` with the standalone script, like you can with the analytics.js script?

`analytics.load('writekey', { integrations: { 'Fullstory': true } })`

Thanks in advance.

Mischa

**Comment by edsonjab** [comment]
Hi @mischasigtermans  you can use the "mapCustomPrefrence", you can see the documentation [here](https://github.com/segmentio/consent-manager#mapcustompreferences).

**Comment by edsonjab** [comment]
@mischasigtermans you can check the (storybook)[https://segmentio.github.io/consent-manager/] with the examples how to use the different escenarios 

(standalone)[https://segmentio.github.io/consent-manager/index.html?path=/story/standalone-javascript--with-customization]
