### ISSUE TITLE
"initialPreference" is not working on standalone script

### ISSUE THREAD

**Issue by arijit-tweb** [segmentio/consent-manager#249]
I added this on my standalone script
`initialPreferences: {
          Functional: true,
          Marketing_and_Analytics: true,
        },`

>But still  "Functional" and "Marketing and Analyics" is not selected "yes" by default.

Also after added "initialPreferences" , **I'm unable to close the banner any more**

![Screenshot (142)](https://user-images.githubusercontent.com/103941380/179724549-5640b56b-7d97-4a39-a781-cf8d0f887339.png)

**Comment by arijit-tweb** [comment]
Now I found some other solution to this, thanks

**Comment by Munter** [comment]
I'm running into the same issue. @arijit-tweb Would you mind telling what this other solution is?

@edsonjab I'm using the example copy/pasted from the README with the write key updated and `initialPreferences: { Functional: true, Marketing_and_Analytics: true, }` added. None of the radio's are pre-filled

**Comment by Munter** [comment]
After stabbing around a bit it looks like these are the correct keys to use when setting `initialPreference`:

```js
      initialPreferences: {
        marketingAndAnalytics: true,
        advertising: true,
        functional: true,
        essential: true,
      },
```

I recommend not using the invalid `{‘Functional’:true}` example in the docs, and possibly show this full config example instead
