### ISSUE TITLE
Excluding destinations from consent manager

### ISSUE THREAD

**Issue by Emmajperrez** [segmentio/consent-manager#253]
Hi there,

I'm trying to have some destinations still be used whatever the answer is for the consent manager.

What the best way to do this?

For context, this destinations are in cloud mode so they don't use cookies on the website. Yet they still need the analytics.page() event I'm triggering on the front-end.

Thanks!

**Comment by edsonjab** [comment]
Hi @Emmajperrez, could you explain more about your problem, please?
