### ISSUE TITLE
Cannot read properties of undefined (reading 'initialized')

### ISSUE THREAD

**Issue by b2kdaman** [segmentio/consent-manager#255]
I tried to implement ConsentManager component for React using the example and receive this error
```
analytics.ts:53 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'initialized')
    at conditionallyLoadAnalytics (analytics.ts:53:23)
    at ConsentManagerBuilder3.<anonymous> (index.tsx:226:5)
    at step (analytics.ts:95:1)
    at Object.next (analytics.ts:95:1)
    at fulfilled (analytics.ts:95:1)
```

**Comment by b2kdaman** [comment]
Here you can see the same result:
https://codesandbox.io/s/1r21mjn8o3

**Comment by edsonjab** [comment]
Hi @b2kdaman  that happens when the app did not have the script on header HTML

you can check this example on NextJS

https://github.com/segmentio/consent-manager#example-in-nextjs

like the section <script>
