### ISSUE TITLE
Standalone CM does not set cookie correctly when calling acceptAll

### ISSUE THREAD

**Issue by seanlail** [segmentio/consent-manager#259]
I set the CM to _not_ track by default, but create a custom "Allow" button that calls the internal "acceptAll" function.

**Expected** outcome:
Cookie to be set with all keys accepted

**Actual** outcome:
All declined.

```js
window.consentManagerConfig = ({ doNotTrack, inEU, preferences, React }) => {
  return {
    bannerActionsBlock: (props) =>
      React.createElement("button", { onclick: () => props.acceptAll() }, "Allow"),  // clicking this button does not accept all cookies?
    bannerContent: React.createElement("span", null, "This site uses cookies"),
    bannerSubContent: "Preferences",
    bannerHideCloseButton: true,
    cancelDialogTitle: "Lorem Ipsum",
    cancelDialogContent: "Lorem Ipsum",
    container: "#segment-cookies",
    cookieName: "tracking-preferences",
    defaultDestinationBehavior: "enable",
    implyConsentOnInteraction: false,
    initialPreferences: {
      functional: false,
      marketingAndAnalytics: false,
      advertising: false,
    },
    preferencesDialogContent: "Lorem Ipsum",
    preferencesDialogTitle: "Lorem Ipsum",
    writeKey: "<segment-key-goes-here>",
  };
};
```

**Comment by seanlail** [comment]
@edsonjab Here's a repo to show the issue: https://github.com/seanlail/segment-cm-issue-259

Create `.env.local` and set the `NEXT_PUBLIC_SEGMENT_APIKEY=<a valid key>` to run it.

**Comment by seanlail** [comment]
@edsonjab I think this is where the bug is: https://github.com/segmentio/consent-manager/blob/a4633dfe3d9f6e6fb64816245b3e768e56b6d9bb/src/consent-manager/container.tsx#L96 
This assumes that the initial preferences are all "enabled" / "true".

**Comment by seanlail** [comment]
My workaround is to call `preferences.savePreferences` manually and then reload the page.
I don't know all the destinations dynamically though.

**Comment by edsonjab** [comment]
@seanlail I will make some test for initialPreferences, like you say maybe there is the bug
