### ISSUE TITLE
Changing copy in Purpose section of table

### ISSUE THREAD

**Issue by eveadele** [segmentio/consent-manager#26]
Hi Segment folks! I'm wondering if there's an easy way I can change the copy in some of the table cells in the consent manager. For example, my company does not have a live chat, so saying "these tools enable you to communicate with us via live chat" is misleading.

Would it be possible for you to either
(a) change the wording to something like "these tools *may* enable you to communicate with us via live chat or
(b) provide a way to override the default copy for the Purpose column of the table?

Thanks!
-Eve

**Comment by nettofarah** [comment]
Hey, Eve!
Yeah, you can customize the consent manager completely.

How are you planning to use it? Through the react component? or through the script tag?

**Comment by eveadele** [comment]
I'd like to use it with the script tag and callback function. Our site doesn't currently use React so I'd like to avoid bringing it in just for one component.

**Comment by felipe-najson-ntf** [comment]
Hi @eveadele, this issue is related to the following issue #137. It is a good feature that we are considering to implement, we will continue the discussion there. Thanks for your contribution!

Greetings, segment team.
