### ISSUE TITLE
Add option to skip/disable analytics.load

### ISSUE THREAD

**Issue by davidbbe** [segmentio/consent-manager#262]
Previous to using the consent-manager I was able to optionally bypass analytics.load with a conditional in the Segment snippet. This is useful when testing development environments and when running end to end tests. The consent-manager took over when analytics.load is used and now my only option to disable the analytics.load is to use `shouldRequireConsent=true` for all dev and testing environments. If there was an options to not run analytics.load in development environments then that would give us better options for testing.

**Comment by busticated** [comment]
2nd'ing this request. it'd be helpful to be able to prevent loading the analytics.js script even if the user has granted consent under certain circumstances (testing, local development, etc). it's worth noting that the `segment/snippet` package exposes the control ([docs](https://github.com/segmentio/snippet#snippetmaxoptions) | [code](https://github.com/segmentio/snippet/blob/8879ab5203083fc698923fb027148ffa23c09cfa/lib/index.js#L93-L103)) though i realize that's a build-time option atm.

**Comment by edsonjab** [comment]
Hi @davidbbe and @busticated we start looking into your suggestion
