### ISSUE TITLE
closeBehavior enum not exported properly

### ISSUE THREAD

**Issue by joelpierre** [segmentio/consent-manager#266]
![Screenshot 2022-09-12 at 23 44 29](https://user-images.githubusercontent.com/8969851/189771284-e3124971-9b69-48a3-bc56-05f26372832b.png)

Can't use the enum that is apparently exported 😅 and when I try to pass the prop it fails

![Screenshot 2022-09-12 at 23 46 49](https://user-images.githubusercontent.com/8969851/189771508-d4d663f4-5be8-4392-b656-6af77fc337d6.png)

**Comment by edsonjab** [comment]
Hi @joelpierre the correct path for CloseBehavior is 
`@segment/consent-manager/container`

you can check out storybook [here](https://segmentio.github.io/consent-manager/index.html?path=/story/react-component-onclose-interactions--accept)

**Comment by mattkoch-bb** [comment]
> Hi @joelpierre the correct path for CloseBehavior is `@segment/consent-manager/container`
> 
> you can check out storybook [here](https://segmentio.github.io/consent-manager/index.html?path=/story/react-component-onclose-interactions--accept)

If I try to import this enum, I get the following...

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/106617936/190256797-da61e7fb-889e-4a39-ac84-ed7f888c9a1d.png">

**Comment by joelpierre** [comment]
Yep same @mattkoch-bb, it isn't exported from that location @edsonjab . I think the issue is when you build for production the type definitions are in a completely different location so TS gets a bit confused, typically they would be exported from the "same" path just the build/dist folder instead.

**Comment by mattkoch-bb** [comment]
@joelpierre How'd you get around it? :-D

**Comment by joelpierre** [comment]
> @joelpierre How'd you get around it? :-D

The dreaded `"..." as any`

**Comment by mattkoch-bb** [comment]
> "..." as any

In your import statement somewhere?

**Comment by joelpierre** [comment]
```ts
const closeBehavior = 'accept' as any;
...
closeBehavior={closeBehavior}
...
```
