### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by atul-jalan** [segmentio/consent-manager#270]
I get the following console warnings after installing the consent manager package. Have tried a variety of different fixes to no avail. Is this a known issue/am I doing something wrong here?

![Screen Shot 2022-09-20 at 12 15 30 PM](https://user-images.githubusercontent.com/54699627/191322466-edeed990-4952-4374-84cc-577be7fdc4e5.png)

I'm using version `5.6.0` of the consent manager and am on version `17.0.2` of react. I did have to use the `--legacy-peer-deps` flag to successfully install the consent manager but feel that that's probably unrelated.

**Comment by edsonjab** [comment]
HI @atul-jalan, could you share us more information about your project configuration please?

**Comment by chrisradek** [comment]
@atul-jalan Thanks for reporting this issue. It looks like the issue is that we aren't publishing the source files that the source-maps point to. Easiest solution for us would be to include `src` in the package.json `files` list.

**Comment by atul-jalan** [comment]
@chrisradek Amazing! Glad it's figured out -- and so quickly too. @edsonjab did you still need more information on my project configuration.

Any idea about when this might get fixed?

**Comment by chrisradek** [comment]
@edsonjab Here's a reproduction using a project built with `create-react-app`: https://github.com/chrisradek/consent-manager-test

You can clone that, then just run:
- `npm install`
- `npm start`

You'll see the sourcemap warnings appear in the console.

**Comment by atul-jalan** [comment]
@chrisradek Thanks for creating that copy.

@edsonjab Our setup is just a `create-react-app` project with webpack. We are on version `17.0.2`. Let me know if you need any other information.

**Comment by edsonjab** [comment]
Hi @atul-jalan.

A quick solution, you can add this flag `GENERATE_SOURCEMAP=false` on your start script like:
`"start": "set \"GENERATE_SOURCEMAP=false\" &&  react-scripts start"`
(this is an windows example)

we will change the configuration on our webpack.config to fix this issue.

**Comment by atul-jalan** [comment]
@edsonjab We use sentry, which relies on sourcemaps to work, so disabling sourcemaps entirely isn't an option for us.

We're currently ignoring the warnings by running the app via `react-app-rewired` instead of `react-scripts` and ignoring console warnings for `@segment/consent-manager` in the `config-overrides.js` file for `react-app-rewired`. Of course, this is a temporary band aid that we'd like to remove, but it's working well for now.

Thank you for your help!
