### ISSUE TITLE
Allow passing additional cookie attributes

### ISSUE THREAD

**Issue by YoannaKaramfilova** [segmentio/consent-manager#273]
Currently it is not possible to specify cookie attributes outside of `cookieName`, `cookieDomain` and `cookieExpires`. There are use cases when specifying other attributes is necessary - for example to set cookies and use the consent manager from embedded apps control over `secure` and `sameSite` attributes is needed.

**Comment by edsonjab** [comment]
hi @YoannaKaramfilova thanks for your report and your PR we are testing your changes
