### ISSUE TITLE
The consent manager preferences dialog didn't open onClick

### ISSUE THREAD

**Issue by henky-wu-qatalog** [segmentio/consent-manager#279]
We get the following error when`openConsentManager()` is called in a `onClick` function. 
The preference dialog didn't open, and an error occurs as follows:
![Screenshot 2022-10-12 at 11 29 42](https://user-images.githubusercontent.com/96086008/195321670-634b59dc-2f5c-4118-8c29-3df8e7845ec0.png)

and we are getting this build warnings in NextJS:
```
../../node_modules/@segment/consent-manager/esm/consent-manager/dialog.js 
Attempted import error: 'nanoid' does not contain a default export (imported as 'nanoid').
```
![Screenshot 2022-10-12 at 11 18 55](https://user-images.githubusercontent.com/96086008/195321744-7898f97c-074f-48f3-9a98-920abcf03fe8.png)

------

we're using:
- consent manager 5.6.0
- nextjs 12.1.0

**Comment by edsonjab** [comment]
HI @henky-wu-qatalog thank you for your report, we start looking into this.

**Comment by edsonjab** [comment]
Hi @henky-wu-qatalog I created this repo with an [example ](https://github.com/edsonjab/next_consent-manager)how configure consent-manager with nextJs. I created a PR to fix the issue with the lodash library

**Comment by henky-wu-qatalog** [comment]
Thanks for the quick turnaround, @edsonjab. 
I just briefly check the [example](https://github.com/edsonjab/next_consent-manager) here but I can only see a nextjs boilerplate project. Would you mind take a look on this?

**Comment by edsonjab** [comment]
Hi @henky-wu-qatalog sorry, I forgot push my last changes, now is updated

**Comment by corydhmiller** [comment]
@edsonjab I cloned your repo but still getting this issue that others have reported.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/4403994/205088725-6631196a-9252-45b1-9297-2b70e5eba484.png">

Importing the banner  dynamically with `next/dynamic` loads the component, but the banner never shows and `openConsentManager` does nothing.

I've been struggling with Next.js and `consent-manager` for the last few days, it doesn't really seem like they want to play nice. Are there any working examples of solutions with up-to-date Next and `consent-manager` versions?

**Comment by edsonjab** [comment]
This issue is fixed on this [PR](https://github.com/segmentio/consent-manager/pull/281). We will release a new version soon.
