### ISSUE TITLE
Always causes reload when rendering ConsentManagerBuilder

### ISSUE THREAD

**Issue by ChrisSargent** [segmentio/consent-manager#280]
When rendering a component which includes the `ConsentManagerBuilder`, the `initialise` function is always called: https://github.com/segmentio/consent-manager/blob/12ec8ee01bf603155d7d748f688d7cd78169063b/src/consent-manager-builder/index.tsx#L179

This in turn always calls `conditionallyLoadAnalytics` specifying a `shouldReload` value, which is by default set as true: https://github.com/segmentio/consent-manager/blob/12ec8ee01bf603155d7d748f688d7cd78169063b/src/consent-manager-builder/index.tsx#L226

In our case this manifests itself as an unnecessary page reload in our SPA as soon as a user goes to our custom 'Cookie Options' page. It seems to me this should not trigger an automatic reload in all cases?

**Comment by edsonjab** [comment]
Hi @ChrisSargent thank you for your report, we start looking into this.
