### ISSUE TITLE
Support adding additional destinations

### ISSUE THREAD

**Issue by lesliepassante** [segmentio/consent-manager#282]
Is there a way to supply additional destinations to `<ConsentManager>` without using the `otherWriteKeys` attribute? We don't want to include all of the destinations that are connected with another source, but just a subset of them. It would be great to have an attribute like `otherDestinations` that would accept an object formatted just like the `/integrations` endpoint:

```
[{
	"name": "Google Universal Analytics",
	"creationName": "Google Analytics",
	"description": "Google Universal Analytics is the most popular analytics tool for the web. It’s free and provides a wide range of features. It’s especially good at measuring traffic sources and ad campaigns.",
	"website": "http://google.com/analytics",
	"category": "Analytics"
}]
```

**Comment by edsonjab** [comment]
Hi @lesliepassante you can use the property customCategories you can check the documentation [here](https://github.com/segmentio/consent-manager#customcategories).

**Comment by lesliepassante** [comment]
@edsonjab Thanks! We tried `customCategories`, but it doesn't look like it will let us include additional destinations that aren't in the destinations you're pulling from Segment's API. Should it?

**Comment by edsonjab** [comment]
oh sorry @lesliepassante, you can check ConsentManagerBuilder and the property [mapCustomPreferences](https://github.com/segmentio/consent-manager#mapcustompreferences) and this [storybook](https://segmentio.github.io/consent-manager/index.html?path=/story/consentmanagerbuilder--category-based)
