### ISSUE TITLE
Can't close consent banner when using customCategories option

### ISSUE THREAD

**Issue by danielj-flycode** [segmentio/consent-manager#284]
We are using consent manager standalone with `customCategories` option on html project, using this code example https://codepen.io/samuelkahr/pen/JjdNqzr?editors=1010. 
But the consent banner wasn't closed when user tried to save the preferences on consent preferences dialog. It was working properly when I remove `customCategories` option. By the way, it worked as expected on React project by using `ConsentManager`

**Comment by danielj-flycode** [comment]
Just realized that similar issue happens on `ConsentManager` component as well, but in different way. By clicking `Save` button on consent management dialog banner closed but after page refreshing it opens up again.

**Comment by edsonjab** [comment]
Hi @danielj-flycode thank you for your report, we start looking into this.

**Comment by danielj-flycode** [comment]
Thanks for your quick response, @edsonjab. I tried to update standalone script package version but the problem was more serious, the page hard-refreshing triggered by clicking any where in the page and I couldn't even open consent management dialog.
