### ISSUE TITLE
Page reloading by clicking Accept all button when passing initialPreferences to consent manager

### ISSUE THREAD

**Issue by danielj-flycode** [segmentio/consent-manager#286]
Page reloading by clicking Accept all button when passing `initialPreferences` to consent manager, It would give user bad UX. It would be great if we have should option to disable page reload.

**Comment by edsonjab** [comment]
Hi @danielj-flycode we created a [PR](https://github.com/segmentio/consent-manager/pull/283) for this request.

**Comment by jackhair** [comment]
> Hi @danielj-flycode we created a [PR](https://github.com/segmentio/consent-manager/pull/283) for this request.

Hi @edsonjab is this option available for the React `ConsentManager` component as an option too? Or just `ConsentManagerBuilder`?

**Comment by edsonjab** [comment]
Hi @jackhair yes theoption 'shourReload' only is available on ConsentManagerBuilder.
