### ISSUE TITLE
Upgrade nanoid to latest version

### ISSUE THREAD

**Issue by henky-wu-qatalog** [segmentio/consent-manager#304]
Related to #279 
#### Issue:
After upgraded to the v5.7.0, we are still getting this build warnings in NextJS:
```
../../node_modules/@segment/consent-manager/esm/consent-manager/dialog.js 
Attempted import error: 'nanoid' does not contain a default export (imported as 'nanoid').
```
#### Problem:
We are currently using `nanoid` version 3.3.4 in our project which required a named import instead of default import 
```
import {nanoid} from 'nanoid';
```
---
Sadly we can't afford to downgrade to an older version, so wonder if it's possible to bump `nanoid` to it's latest version? Thanks! (or any other workarounds will be appreciated)

**Comment by edsonjab** [comment]
Hi @henky-wu-qatalog  thank you for your report, we start looking into this.
