### ISSUE TITLE
Some meta tags getting lost

### ISSUE THREAD

**Issue by mmejiadeveloper** [segmentio/consent-manager#308]
Hi!

Sometime ago we added this consent-manager to our website. Recently it was found a situation where some meta tags that are needed are not being loaded.
An investigation was made by a team mate and he determinated that this was caused by the consent-manager implementation.

So i started to look to the code that was added and i found that the component `ConsentManagerBuilder` is the piece that is causing this issue.

Here is a screenshot of this component being used

![image](https://user-images.githubusercontent.com/21294790/223784435-e4c9d8b8-6347-4f59-a1c6-2f0b7160137c.png)

In my site there should be a tags that are normally created based on some external services

![image](https://user-images.githubusercontent.com/21294790/223784975-bdfd1203-8d69-4fbc-8016-8feaec32c60c.png)

As you can see im using `property=“og` as the attribute these tags always contain

Now im going to remove all of the implementation of `ConsentManagerBuilder` this way:

![image](https://user-images.githubusercontent.com/21294790/223785509-ec38c1aa-29cd-49de-9cf2-2baf6e91dec5.png)

Now I have 6 tags

![image](https://user-images.githubusercontent.com/21294790/223785462-cf9a985c-e83f-46ff-b219-412c62e63ebe.png)

Is this a known issues? Is there any workaround this for this? Would be this fix by going for the stand-alone implementation?

Thanks for your soon response

**Comment by edsonjab** [comment]
Hi @mmejiadeveloper  thank you for your report, we start looking into this.

**Comment by edsonjab** [comment]
Hi @mmejiadeveloper sorry to answer late, I was searching the solution, with stand-alone implementation it doesn't happen. You can try using this implementation I will work on the solution with 'ConsentManagerBuilder'
