### ISSUE TITLE
window.analytics.user().traits() vs tracking-preferences document.cookie

### ISSUE THREAD

**Issue by j-quelly** [segmentio/consent-manager#311]
When I explicitly set my tracking preferences in the EU `window.analytics.user().traits()` returns my preferences as expected. 

However, when I implicitly consent to all tracking, my preferences are not saved to `window.analytics.user().traits()` instead they're saved to a `tracking-preferences` cookie. I'm curious why the consent manager does not mutate the object returned from `window.analytics.user().traits()`? 

Does segment analytics v2 parse the `tracking-preferences` cookie in addition to the `window.analytics.user().traits()`?

**Comment by edsonjab** [comment]
Hi @j-quelly thank you for your report, we start looking into this.

**Comment by edsonjab** [comment]
HI @j-quelly sorry for the delay, the information will be saved on two places like the next image:
![image](https://github.com/segmentio/consent-manager/assets/22898327/d48c7c02-2f11-4396-b4ef-d4d5a0bfaa7e)

for you second question, no, analytics v2 read all the cookies set on the page and search the preferences with a different name. You can check [this file](https://github.com/segmentio/analytics-next/blob/master/packages/browser/src/test-helpers/browser-storage.ts) to see that
