### ISSUE TITLE
Feature: Allow the change of default categories

### ISSUE THREAD

**Issue by Nightapes** [segmentio/consent-manager#313]
We have the requirement to set Google Tag Manager as Essential. We tried to set custom categories, but the issue is that we can not mark a category as essential. The user can deny the essential category. 

![Screenshot 2023-03-24 at 08 38 25](https://user-images.githubusercontent.com/15911153/227455451-f541655f-5c19-4583-b4b8-150ac0710c63.png)

Solutions:

* Extend custom category type to be the same as the build in type. And overwrite internal categories instead of have a separate handling for it.  https://github.com/segmentio/consent-manager/blob/877542fc37d6f497b5fc18298dea0702550ab990/src/types.ts#L76 

* Allow the overwriting via settings from the default mapping https://github.com/segmentio/consent-manager/blob/877542fc37d6f497b5fc18298dea0702550ab990/src/consent-manager/categories.ts#L15

**Comment by edsonjab** [comment]
Hi @Nightapes thank you for your report, we start looking into this.

**Comment by edsonjab** [comment]
HI @Nightapes we created a new PR #333 to set 'N/A' to any value on CustomCategories, is this Pull Request helps to solve your issue?

**Comment by Nightapes** [comment]
@edsonjab Thanks for the implementation. Looks good from my side, waiting for the release
