### ISSUE TITLE
Bug: Standealone CSS

### ISSUE THREAD

**Issue by Nightapes** [segmentio/consent-manager#314]
Not possible to use custom css with standalone.js. 

We have the issue that with every release the css names changes, which makes it a pain to update the script.

Every css has a random id at the end like `#consent-container .css-1uzjr4x`

Is there a better way to style the standalone script?

**Comment by edsonjab** [comment]
Hi @Nightapes thank you for your report, we are working on a new version to add css properties and Ids to each element.
