### ISSUE TITLE
Custom destinations to Essential category but maintaining the N/A value

### ISSUE THREAD

**Issue by rafaelluz-f** [segmentio/consent-manager#331]
Can we add new destinations to the Essential category but maintain the N/A value? If is still not possible, could be added?

Actual result:
![image](https://user-images.githubusercontent.com/17931282/235815879-c8960cc7-5db9-408b-a348-de2ff21e38c4.png)

Expected result (example):
![image](https://user-images.githubusercontent.com/17931282/235815569-9652f4e5-2383-4f03-9412-ac467d5cb3c6.png)

I created a pull request for it: https://github.com/segmentio/consent-manager/pull/332

**Comment by rafaelluz-f** [comment]
@edsonjab thank you for helping me with this. I appreciate your fast answer with your [pr](https://github.com/segmentio/consent-manager/pull/333, could I ask for the ETA?

**Comment by michaelseanbecker** [comment]
I was working with this today (5.8.1 tag) and noticed that when preferences are saved the `N/A` changes to `True|False`

Initial load (not dismissing cookie banner)
![image](https://github.com/segmentio/consent-manager/assets/1079656/ba75b936-b93e-48a7-83cc-09272c35d4c8)

After save:

![image](https://github.com/segmentio/consent-manager/assets/1079656/1b3871b8-1503-4f1e-9850-28eeeaf8bebe)
