### ISSUE TITLE
Consent Manager Builder on Render 

### ISSUE THREAD

**Issue by Bedrock02** [segmentio/consent-manager#337]
Analytics isn't loaded properly until a user interacts with the modal. After interacting with modal the tracking preferences are respected...looking to find a way for preferences to be acknowledged on render and without having to touch the modal.

**Comment by edsonjab** [comment]
Hi @Bedrock02 thank you for your report, could you help us to explain the next details please:

what framework and what version are you using?
What version of Consent-manager?

**Comment by Bedrock02** [comment]
> Hi @Bedrock02 thank you for your report, could you help us to explain the next details please:
> 
> what framework and what version are you using?
> What version of Consent-manager?

@segment/consent-manager ^5.7.0
 Framework: NextJs 13.1.6

**Comment by edsonjab** [comment]
you can use the property `shouldRequireConsent` [here](https://github.com/segmentio/consent-manager#shouldrequireconsent), check if that property helps to solve your issue.

**Comment by Bedrock02** [comment]
Side note: Am I setting this up correctly?

Before we were using the standalone script so we kept some of it because I saw that without it the consent builder doesn't load.

```typescript
<ModalContainer toggleModal={toggleModal} mounted={isModalOpen}>
   <StudioConsentModal content={consent_fields} toggleModal={toggleModal} />
</ModalContainer>

{/* TODO: Do We need This? */}
<Script id="segment-service">
        {`
          !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var key=analytics.methods[e];analytics[key]=analytics.factory(key)}analytics.load=function(key,e){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=e};
          analytics._writeKey="${process.env.NEXT_PUBLIC_SEGMENT_API_KEY}";
          analytics.SNIPPET_VERSION="4.15.3";
          analytics.page();
          }}();
        `}
</Script>
```

**Comment by Bedrock02** [comment]
@edsonjab just following up with some new information.

The user's consent settings get applied once the ConsentManagerBuilder is rendered on the page. If it is never rendered those setting are never respected. Looking to see if there is a way that we can `initialize` before the ConsentManagerBuilder renders (if it is even clicked)

**Comment by Bedrock02** [comment]
[Solution]

Ended up calling `analytics.load` with preferences from existing cookie on page render. I no longer need to wait for the modal to open up.

```typescript
const wd = window as WindowWithAJS;
const preferences = loadPreferences();

useEffect(() => {
  if (preferences && wd.analytics && wd.analytics.load) {
    wd.analytics.load(
      `${process.env.NEXT_PUBLIC_SEGMENT_API_KEY}`,
      { integrations: preferences.destinationPreferences }
    );
  }
}, [preferences, wd]);
```
