### ISSUE TITLE
Custom Segment endpoint

### ISSUE THREAD

**Issue by guillaume-ro-fr** [segmentio/consent-manager#34]
According to the [`analytics.js` integration documentation](https://segment.com/docs/sources/website/analytics.js/#proxy), the Segment CDN endpoint can be personalized with a private endpoint.

The [fetch destinations function](https://github.com/segmentio/consent-manager/blob/49d1ed58b70ad9a59ac5ea54f7b988eac6e38dc2/src/consent-manager-builder/fetch-destinations.js#L6) has a hard-coded URL in parameters.

Maybe the host part of the URL must be available in the parameters 😄.

**Comment by pooyaj** [comment]
Resolved in https://github.com/segmentio/consent-manager/pull/110
