### ISSUE TITLE
Consent Manager being truncated on iPhoneX

### ISSUE THREAD

**Issue by c-noonan** [segmentio/consent-manager#37]
It looks like the consent manager is being truncated on iPhone X, while it’s fully visible on larger screens such as iPhone XR.

Is there a way to improve mobile rendering so the entire modal is visible for all users, e.g. iPhone X screens? Thanks!

**Comment by JaKXz** [comment]
Can confirm I am seeing this issue as well using `"@segment/consent-manager": "^1.3.1"`

**Comment by nettofarah** [comment]
Hey!
Would you mind testing it against something > 2.0.0?

**Comment by JaKXz** [comment]
@nettofarah would you mind publishing release notes for v2 and 3? Are there any other breaking changes to be aware of? I noticed the default for `implyConsentOnInteraction` was changed, but not sure if I missed anything else.

**Comment by nettofarah** [comment]
hey @JaKXz just published a new version of the consent manager that now includes a changelog: https://github.com/segmentio/consent-manager/blob/master/CHANGELOG.md

**Comment by JaKXz** [comment]
Thanks @nettofarah - what changed in v3?

**Comment by nettofarah** [comment]
@JaKXz `implyConsentOnInteraction` now defaults to `false`
https://github.com/segmentio/consent-manager/blob/master/CHANGELOG.md#300oct-8-2019
