### ISSUE TITLE
Keep getting error - Failed to find a valid digest in the 'integrity' attribute for resource - Please help!

### ISSUE THREAD

**Issue by Nbennett650** [segmentio/consent-manager#39]
I am new to Segment and coding. I don't know what I am doing wrong!

I keep getting the error:
Failed to find a valid digest in the 'integrity' attribute for resource 'https://unpkg.com/@segment/consent-manager@1.2.0/standalone/consent-manager.js' with computed SHA-256 integrity 'wC00Ta5lCOuOSL3dT3NF9tb9roS8uxTPGQ2Iqe70cqo='. The resource has been blocked.

```
<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
  analytics.page();
  }}();
</script>  

<div id="consent-manager-container" style="position: fixed; left: 0; right: 0; bottom: 0; z-index: 100;">
<script
  src="https://unpkg.com/@segment/consent-manager@1.2.0/standalone/consent-manager.js"
  integrity="sha256-N/wC00Ta5lCOuOSL3dT3NF9tb9roS8uxTPGQ2Iqe70cqo="
  crossorigin="anonymous"
  defer
  data-container="#target-container"
data-writeKey="Replacement for write key for Github"
  data-bannerContent="We use cookies (and other similar technologies) to collect data to improve your experience on our site."
  data-bannerSubContent="You can change your preferences at any time."
  data-preferencesDialogTitle="Website Data Collection Preferences"
  data-preferencesDialogContent="We use data collected by cookies and JavaScript libraries to improve your browsing experience, analyze site traffic, deliver personalized advertisements, and increase the overall performance of our site."
  data-cancelDialogTitle="Are you sure you want to cancel?"
  data-cancelDialogContent="Your preferences have not been saved. By continuing to use our website, you՚re agreeing to our Website Data Collection Policy."
></script>
</div>

```

**Comment by ianwremmel** [comment]
Seeing the same thing in Firefox. I ended up using the jsdelivr version instead of unpkg:

https://www.jsdelivr.com/package/npm/@segment/consent-manager

**Comment by finn-arron** [comment]
Hi, 

Could it be that your ID and the data container are different?

**Comment by Uysim** [comment]
Get the same error. Know how to fix it?

**Comment by ianwremmel** [comment]
There are probably only two things that can cause this error:
1. When the most recent version was published, the incorrect SHA was added to the docs (maybe a typo, maybe a mistake when generating it)
2. The code on the CDN is compromised and shouldn't be used.

@Uysim as consumers, there's really no fix, the best we can do is use a different CDN and hope it's not been compromised. Hopefully someone from segment can address the security concerns here soon.

@fforres can you take a look? (apologies for tagging you, but you appear to be the only committer on GitHub)

**Comment by JulienDemarque** [comment]
Got the same error and found the answer here (see Rowno message): https://github.com/segmentio/consent-manager/issues/11
What i did is copy the file on my computer, open terminal and run the command line like shown.

**Comment by JulienDemarque** [comment]
Nevertheless, giving the sha alone works but the following error pops up in the console:
"Error parsing 'integrity' attribute ('LAQMAHhPEo3eDEjNt4kTfZCELOuioQi+b5BoZtqbunE='). The hash algorithm must be one of 'sha256', 'sha384', or 'sha512', followed by a '-' character."
Adding "sha256-" to the integrity attribute then does not work at all... Not sure why.

**Comment by ianwremmel** [comment]
that's...not a great solution. that assumes that the file hasn't been compromised when you download it and therefore the SHA you generate will protect you in the future. while it's *probably* fine, it mostly defeats the purpose of SRI. It would be really great if Segment could get a proper fix out.

**Comment by ianwremmel** [comment]
I've opened a support ticket in the hopes that someone on the security team will see it.

**Comment by danielstjules** [comment]
The new install instructions should work without integrity check!

**Comment by ianwremmel** [comment]
So, wait, is the new recommendation to just not bother doing an SRI check and hope for the best?
