### ISSUE TITLE
ConsentManagerBuilder dont show preferences

### ISSUE THREAD

**Issue by msaglietto** [segmentio/consent-manager#41]
Hello :wave: 

I have in the site a consent manager and after the answering to it the local storage has this information:
```
ajs_user_traits:"{"destinationTrackingPreferences":{ Salesforce: true },"customTrackingPreferences":{"marketingAndAnalytics":true,"advertising":false,"functional":false}}"
```
So then on another part of the site to read the values I dont want to hardcode the access to the local storage so what I did is a ConsentManagerBuilder .. 
```
<ConsentManagerBuilder writeKey={config.SEGMENT_WRITE_KEY}>
        {({ preferences, destinations }) => { 
```

My problem is that the preferences are coming with the value Salesforce but not marketingAndAnalytics .. 

I try adding a mapCustomPerferences like https://github.com/segmentio/consent-manager/blob/master/src/consent-manager/index.js#L106 but its never called =S

So why are the preferences coming up empty ? There is a better way of just reading the preferences ?

Thanks

**Comment by msaglietto** [comment]
Actually the custom marketingAndAnalytics show when I complete the consent but refresh the page and dont show anymore

**Comment by felipe-najson-ntf** [comment]
Hi msiglietto, sorry for the late reply. You can access the categories through the destination object. As described here
https://github.com/segmentio/consent-manager#destinations

Example:
![image](https://user-images.githubusercontent.com/89416739/134191280-4e048465-9149-4a6c-8f10-05e6a4822441.png)

Output:
![Screen Shot 2021-09-21 at 11 36 09](https://user-images.githubusercontent.com/89416739/134191301-4babd3f2-3018-475c-81b8-83a084e1051e.png)

Hope it helps you, regards segment team.
