### ISSUE TITLE
JS-Cookie Error: SyntaxError: Unexpected token e in JSON 

### ISSUE THREAD

**Issue by lyonsv** [segmentio/consent-manager#44]
Hi there 👋 ,

The following error occurs when using Brave: Version 0.67.125 Chromium: 76.0.3809.100.

```SyntaxError: Unexpected token e in JSON at``` is thrown from js-cookies on mount. 

I'm using ```Consent Manager``` and ```openConsentManager``` from ```@segment/consent-manager```, and ```@segment/in-eu```

The consent manager fails to open, and no error is logged other than the original JSON/js-cookies one.

Not critical to resolve for customers using tracker blocking - but probably could be handled in some way?

**Comment by nettofarah** [comment]
Hey, @lyonsv.
Would you mind providing a sample repository or a codesandbox we could use to try and reproduce the issue?

**Comment by lyonsv** [comment]
@nettofarah I'll see today if this is still an issue after the updates to the library, and post results or close this issue as required

**Comment by felipe-najson** [comment]
Hi everyone! Sorry for the late reply. As @nettofarah says, we need more information or an example to reproduce the error. In this case we didn't get a response, so we will be closing this issue.

Thanks, segment team.

**Comment by felipe-najson-ntf** [comment]
Hi everyone! Sorry for the late reply. As @nettofarah says, we need more information or an example to reproduce the error. In this case we didn't get a response, so we will be closing this issue.

Thanks, segment team.
