### ISSUE TITLE
How to whitelist tracking scripts with Consent Manager

### ISSUE THREAD

**Issue by BrunoBoehm** [segmentio/consent-manager#5]
Hi I'm currently testing the simplest script you've made, works well! 
To the point: some trackers like Google Analytics (when set up correctly with anonymous IP etc.) don't handle PII anymore. **How can I make sure they can be included before user consent (since they' don't need to be acknowledged and accepted by the user anymore), while using your standalone script.**
Otherwise quite a lot of visitors will visit the site, never accept any of the trackers, even those managed by Segment that don't include PII anymore.
Thanks
Bruno

**Comment by nettofarah** [comment]
Hey, @BrunoBoehm.
Thanks for trying out the consent manager :)

It sounds like you might wanna load GA outside of the consent manager in this case, probably as its own script tag, and not load it through Segment, so you could bypass the Consent Manager altogether.

I think one other option would be try to use the advanced `ConsentManagerBuilder` react component and manually call the `setPrerences` and `saveConsent` functions.
Here's an example of how to use the ConsentManagerBuilder: https://github.com/segmentio/consent-manager/blob/master/tools/stories/tool-based.js#L17

**Comment by BrunoBoehm** [comment]
Ok thank you very much for this! 
Loaded out of segment it would mean I could not use my segment trackers anymore, quite a loss.
I'm still trying to figure out if GA (with anonymous IP, URLs without any PII...) would still need user consent based on GDPR requirements... We'll all see how it goes in the following days.
Cheers

**Comment by nettofarah** [comment]
No worries, @BrunoBoehm 
Everyone is kind of learning as they go 😅 
Please let us know if we can help you in any other way, and good luck!
