### ISSUE TITLE
SyntaxError: Unexpected identifier  

### ISSUE THREAD

**Issue by lyonsv** [segmentio/consent-manager#50]
I can't run my app in next.js after upgrading to 3.0.0. The same issue occurs for 2.4.0 installed from npm. 

The error I'm getting in console is:

![image](https://user-images.githubusercontent.com/2531232/66565105-88b9b780-eb59-11e9-8bf4-a696017749f1.png)

I see that in ```node_modules/@segment/consent-manager/commonjs/index.js``` that the file is using imports.

**Comment by nettofarah** [comment]
uh oh. Can you try with v4 to see if the problem still persists?

**Comment by nettofarah** [comment]
@lyonsv just fixed the commonjs build: https://github.com/segmentio/consent-manager/commit/b4f84dfd43c49451ed0d2da5a780f3131c038a80

**Comment by lyonsv** [comment]
@nettofarah that's resolved, thanks!
