### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by haletothewood** [segmentio/consent-manager#55]
Trying to consume this package within a typescript project is currently not possible to my knowledge as there is no `@types` declaration.

I may be missing something as I'm quite new to typescript.

Is this something that is/could be worked on?

**Comment by cookiescrumbs** [comment]
@haletothewood We use Angular and typescript and have successfully integrated the consent manager  into our app. Unfortunately you can't consume this as a package in your project.json. 
You'll need to load it in via script tags in your html.

**Comment by nareshbhatia** [comment]
Surprising that the source is in TypeScript, but the import of @segment/consent-manager is giving the following warning:

> TS7016: Could not find a declaration file for module '@segment/consent-manager'

Same with @segment/in-eu

**Comment by felipe-najson-ntf** [comment]
Hi everyone! Sorry for the late reply, we finally fixed this issue. The path to types directory was wrong but as you can see with pr #126 this was fixed.

Segment team.
