### ISSUE TITLE
Tracking before consent given

### ISSUE THREAD

**Issue by cookiescrumbs** [segmentio/consent-manager#56]
I've noticed that the behaviour of the consent manager on the Segment website is different to the behaviour when implemented  in my app. 

On the Segment website, data is collected even before I agree / close the dialog box or open the preferences.

On my app, data isn't collected until I open the preferences, choose and save. I live in within the EU, so I  believe this behaviour is correct. A user must consent before data can be collected.

Is this right? Or can I do what the Segment implementation does and start the analytics integrations before the the user has consented and if so, what configuration do I require to enable this? 

Thanks :)

**Comment by borisrorsvort** [comment]
@cookiescrumbs Might be because you have set initial preferences to true. If yes then it’s related to https://github.com/segmentio/consent-manager/issues/122

**Comment by felipe-najson-ntf** [comment]
@cookiescrumbs @borisrorsvort Thanks for your contribution. I adhere to what Boris says. If you continue to have problems, feel free to open a new issue. 
We will close this issue and continue the discussion in #122.

Segment Team

**Comment by nd4p90x** [comment]
Please feel free to follow the new issue as @felipe-najson-ntf suggests.  Thank you
