### ISSUE TITLE
Change the UI of Preferences Dialog

### ISSUE THREAD

**Issue by thoreyjona** [segmentio/consent-manager#6]
Is there any way to change the look of the Preferences Dialog? For example make the green Save button in another color and change the buttons in the cancel dialog etc..
Thanks in advance :)

**Comment by nettofarah** [comment]
Hey, @thoreyjona.
Thank you for trying out the Consent Manager :)

You're probably gonna want to use the `ConsentManagerBuilder` in this case. The react component should give you the ability to completely customize the consent manager. (here's an example: https://github.com/segmentio/consent-manager/blob/master/tools/stories/tool-based.js#L17)

Another idea is that you could try and use css to override the styles for the button.

I just tried this css selector on our live demo and was able to get the following result:

```css
div[data-consent-manager-dialog] button[type="submit"] {
  background: blue;
}
```

![image](https://user-images.githubusercontent.com/270688/40510852-c1a18800-5f52-11e8-998d-7edcb99d2de6.png)
