### ISSUE TITLE
Cookie banner closes on page click and cannot be made visible again 

### ISSUE THREAD

**Issue by BrunoBoehm** [segmentio/consent-manager#7]
Hi, 

**What happens:** when the banner appears on the first visit, if you click anywhere else on the page, the banner disappears (this seems to be "implicit consent" - no sure it is quite GDPR compliant). Once it is gone there is no way to bring it back.

In your latest blog post you wrote "The visitor can, of course, access the modal to change their preferences at any time by clicking on the “Website Data Collection Preferences” link in the footer of our site." => How ?

**What should happen instead:**
1. The banner should behave in a way it HAS TO be closed using the "close X" only, not by external click
2. There should be a way to bring the banner back. Ways to achieve that include a link (included wherever necessary - like privacy policy page, footer...)  that would call the "preferences" modal
3. Maybe there should be a parameter in the script to have the banner appear at every page and connection until the preferences pages has not been visited and saved (to increase compliance with GDPR).

Thanks for your feedback on these points!
Cheers

**Comment by hughns** [comment]
The `implyConsentOnInteraction` option (https://github.com/segmentio/consent-manager#implyconsentoninteraction) might help you out on the first question.

For the second question you can create a link that calls `window.consentManager.openConsentManager()` in your footer (or elsewhere).

**Comment by Rowno** [comment]
Yep @hughns is right, the `implyConsentOnInteraction` option and the `window.consentManager.openConsentManager()` function are what you want. 🙂
