### ISSUE TITLE
Unavoidable implied consent with implyConsentOnInteraction

### ISSUE THREAD

**Issue by ashokdelphia** [segmentio/consent-manager#71]
When using the implyConsentOnInteraction flag, I noticed some odd behaviour when trying to opt out. Unfortunately, this effectively makes it impossible to opt-out when this flag is set.

Steps to reproduce:

- clear all cookies for segmentio.github.io
- visit https://segmentio.github.io/consent-manager/index.html?path=/story/react-component-basics--basic-react-component-with-implied-consent
- witness the consent banner at the top of the story page
- follow the "You can manage your preferences here!" link in the banner
- in the "Website Data Collection Preferences" dialog that appears, choose "no" for one of the options, which should work as expected
- try to choose "no" for a second option
- witness that the second option was selected as "yes", along with all other unselected options and that the consent banner in the background page has disappeared
- before hitting save, check which cookies have been set on segmentio.github.io

Expected behaviour:

- selecting "no" works for each choice
- no tracking behaviour fires or cookies are set until the user hits Save

Actual behaviour:

- trying to choose "no" beyond the first choice selects "yes" on all other choices
- tracking happens as soon as the mis-selected item is picked

I presume that interactions with the consent manager form are being mis-interpreted as 'interaction' implying consent.

Unfortunately, this means that with this flag enabled it's not possible for someone to properly opt out, as even if they notice that their selection for "no" was not honoured (and fix it before hitting Save) then the tracking scripts have already fired.

I tried this in a variety of browsers on a Mac OS (10.15.2) machine, with the same behaviour in each; I can't readily test on other OSes but expect the behaviour to be consistent:

- Safari 13.0.4 (15608.4.9.1.3)
- Chrome 79.0.3945.88 (Official Build) (64-bit)
- Firefox 71.0 (20191202093317)

**Comment by elsamjoll** [comment]
Also happening to me, this makes it so much harder for the user to opt out.

**Comment by ashokdelphia** [comment]
Is there any update here?

It's impossible to respect a user's desire to opt-out of tracking if this feature is enabled.

**Comment by felipe-najson-ntf** [comment]
Hi @ashokdelphia @elsamjoll, sorry for the late reply.
This issue has been fixed and there is no such bug in the lastest version of the library. I tested it in chrome, firefox and safari and it works fine.

**Current Behavior**
- When you click once on the Website Data Collection Preferences table, set all the fields to true (preference taken by the team)
- From here you can change the category consent according to your preference. When you switch between true or false no strange behavior occurs.
- Until you accept the consent, the tracking does not begin and the cookies are not set either.

I hope it helps you, segment team.
