### ISSUE TITLE
Questions: invalidating consent + logging/tracking consent

### ISSUE THREAD

**Issue by clemblanco** [segmentio/consent-manager#74]
### Can we invalidate and ask for consent again?

It looks like if some changes are made to the destinations added/removed to some categories, we need to invalidate the current consent and ask for the user consent again.

Is it something the `consent-manager` covers? Or is it something we have to determine ourselves and use the `shouldRequireConsent` prop for?

### Can we track consents when given?

It looks like we need to store/track whenever a consent is given by a user.

How would you recommend to approach this? 

When reading the readme I can see:

> The user's tracking preferences are sent as an identify trait (if they haven't opted out of everything) so that you can also access them on the server-side and from destinations (warehouse).

Can you please expand on that? Does this also work with anonymous users? How to set it up so I can see/report on all the consents?

**Comment by felipe-najson-ntf** [comment]
Hi @clemblanco, I will answer your questions below.

**Can we invalidate and ask for consent again?**
Once the user accept the consent, the information is saved into a cookie and until that cookie expires or is manually deleted. The banner will not appear again.

In case you want a new destination is added to segment you can manage the behavior of the banner with the property "defaultDestinationBehavior". I leave you a link to the docs.
https://github.com/segmentio/consent-manager#defaultdestinationbehavior

**Can we track consents when given?**
Answering your question. Consents cannot be tracked until the user accepts them. Therefore, before that point nothing can be tracked.

Once you accept the consents these are saved in a cookie. From that point, information is sent to the destinations configured in segment (Gooogle Analytics, MixPanel, Postgres and more) if you accepted the consents for that category.

An alternative that you can take if you want to track what consents you accept, is to use a third-party library like js-cookie to manipulate the cookie information and send it to segment through an analytics.track () event.

Hope this answers your questions. Greetings and any other questions, feel free to ask.
Thanks, segment team.
