### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by morrislaptop** [segmentio/consent-manager#75]
Are there any guides on how to integrate this with Vue? (We don't use React)

**Comment by jrpersico** [comment]
Have you found a solution to integrate it with vue.js ?

**Comment by felipe-najson** [comment]
Hi everyone! Sorry for the late reply. I will be giving an update on this in the next few days.

On the other hand, I will close this issue and continue the discussion in another issue since it is duplicated. Thank you for your contribution!
Duplicate of #106 

Segment Team.

**Comment by felipe-najson-ntf** [comment]
Hi everyone! Sorry for the late reply. I will be giving an update on this in the next few days.

On the other hand, I will close this issue and continue the discussion in another issue since it is duplicated. Thank you for your contribution!  
Duplicate of #106

Segment Team.
