### ISSUE TITLE
Unable to access save/cancel buttons in preferences modal on mobile

### ISSUE THREAD

**Issue by MaisonDeVolonte** [segmentio/consent-manager#76]
Device: iPhone X 13.3.1
Browser: Mobile Chrome 80.0.3987.95

![IMG_7892-2](https://user-images.githubusercontent.com/11622069/74769507-7166a580-5282-11ea-822d-0cb17fa9a977.png)

**Comment by BradDenver** [comment]
I also have a user having this issue on iPhone X on our site as well as when they click the Website Data Collection link in the footer of https://segment.com/

**Comment by camwest** [comment]
This fixed it for me:


<img width="611" alt="Screen Shot 2021-09-06 at 9 53 55 PM" src="https://user-images.githubusercontent.com/22905/132272354-2ecfceea-d16f-4082-8c5e-accd34289700.png">
