### ISSUE TITLE
Add id to consent manager form

### ISSUE THREAD

**Issue by MaisonDeVolonte** [segmentio/consent-manager#77]
Can we add an id to the consent manager form? 

Preferably something in readable format like "Consent-Form" or "Cookie-Consent-Form"

I use form ids as identifiers when tracking form submission events:

`analytics.track('Submitted {{Form ID}}', {
    category: 'Form',
    label: '{{Page Path}}',
    value: 0
  });`

<img width="718" alt="Reach_Marketing" src="https://user-images.githubusercontent.com/11622069/74848543-ae3ca600-532f-11ea-9748-4782ae0f1fd9.png">
<img width="719" alt="Sources_-_RoyaltyExoticCars_com_-_Segment-3" src="https://user-images.githubusercontent.com/11622069/74848534-ac72e280-532f-11ea-9a86-f22c2e6e283d.png">
<img width="718" alt="Sources_-_RoyaltyExoticCars_com_-_Segment-2" src="https://user-images.githubusercontent.com/11622069/74848538-ada40f80-532f-11ea-84c9-8c1384e5b8a0.png">
<img width="715" alt="Google_Tag_Manager-2" src="https://user-images.githubusercontent.com/11622069/74848527-aa108880-532f-11ea-8c2f-b8d9a1afec1d.png">

**Comment by felipe-najson-ntf** [comment]
Hello @MaisonDeVolonte, sorry for the late reply.

Thanks for your contribution, I will be evaluating it and consulting it with the team.
I will give you an answer in these days.
