### ISSUE TITLE
Update Consent Manager version in cdn script, add inRegions to to callback options

### ISSUE THREAD

**Issue by samuelkahr** [segmentio/consent-manager#78]
Currently, in the code examples we reference version 4.0.0 of the consent manager. 

<img width="1195" alt="Screen Shot 2020-03-03 at 12 53 42 PM" src="https://user-images.githubusercontent.com/54959899/75818725-43876380-5d4e-11ea-9bc0-a22f0735b3cf.png">

Per [NPM](https://www.npmjs.com/package/@segment/consent-manager), this should be updated to 4.3.0. This new version allows you to create custom categories/tool mappings in the preferences dialog box, as well as exposing the  [inRegions component ](https://www.npmjs.com/package/@segment/in-regions)

**Comment by felipe-najson-ntf** [comment]
Hi @samuelkahr, as @notfelineit mentions, this issue has been resolved and we are currently on version 5.2.0 of consent manager.

Segment team
