### ISSUE TITLE
Add prop to set className of banner container in ConsentManager React component

### ISSUE THREAD

**Issue by lopno** [segmentio/consent-manager#80]
I doesn't seem like there is a way of setting the class name of the banner container when using the ConsentManager React component.
This makes positioning the banner difficult.
I would like a feature like `container: '#target-container',` when using the consentManagerConfig with the standalone script.

Right now in order to position the banner I had to access the div like this:
```
#root > div:first-child {
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 1000;
}
```
This would break my app if the banner was the second element instead of the first as it is now. And since I cannot control where it is put in the DOM this solution seems extremely brittle.

![image](https://user-images.githubusercontent.com/5586960/76403263-f0806280-6384-11ea-81a1-0d53aa0c7732.png)

The first child of `#root` is the banner container and the second child is my app. As you can see there is no class or id on the banner container, so I cannot access it reliably in my css.

**Comment by felipe-najson-ntf** [comment]
Hi @lopno, it seems you're using ConsentManager component. The component does not have a property to add styles but what you can do is wrap the component 'ConsentManager' inside a div and customize that container.

Example
<img width="618" alt="Screen Shot 2021-09-20 at 11 35 17" src="https://user-images.githubusercontent.com/89416739/134020866-3b8921a0-461d-46b3-a2a4-f332b9f917b5.png">

Hope this can help you, Segment team
