### ISSUE TITLE
Updating outdated dependencies

### ISSUE THREAD

**Issue by vitaly-latacora** [segmentio/consent-manager#97]
Hey folks, in looking at this tool, we noticed a number of outdated dependencies, judging by the output of `npm i --package-lock-only` and `npm audit`. We also noticed a few pull requests from dependabot. Some have security implications, including cross-site scripting. Most are several deps down the chain, and some may just be false positives or have no bearing on consent-manager.  We're wondering if this is kept track of internally to determine what needs updating, or in general whether we should worry about these outdated deps?

**Comment by Dezzymei** [comment]
👍

**Comment by Dezzymei** [comment]
I also have two audit issues from npm:

│ Low           │ Regular Expression Denial of Service                         │
│ Package       │ debug                                                        │
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
│ Dependency of │ @segment/consent-manager                                     │
│ Path          │ @segment/consent-manager > @segment/top-domain >             │
│               │ component-cookie > debug                                     │
│ More info     │ https://npmjs.com/advisories/534                             │


│ Low           │ Denial of Service                                            │
│ Package       │ node-fetch                                                   │
│ Patched in    │ >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9                      │
│ Dependency of │ @segment/consent-manager                                     │
│ Path          │ @segment/consent-manager > isomorphic-fetch > node-fetch     │
│ More info     │ https://npmjs.com/advisories/1556

**Comment by felipe-najson-ntf** [comment]
Hi @vitaly-latacora @Dezzymei. I just left a pr #170 open which updates the library's dependencies and fixes its vulnerabilities. We will be working these days to merge it.

Thanks, Segment team
