### ISSUE TITLE
implyConsentOnInteraction not setting consent

### ISSUE THREAD

**Issue by federico-fiorini** [segmentio/consent-manager#99]
`implyConsentOnInteraction: true` setting doesn't seem to work as expected. When clicking on the page it closes the the banner as expected but consent is not implied and events don't start being tracked. Also on page refresh the banner pops up again because the preferences hadn't been set.

[Here's a screen record](https://share.getcloudapp.com/Jrubq2ze) where you can see that even after interacting with the page and the banner closing, on page refresh the banner pops up again and no preferences have been set. The main issue is that events are not tracked.

**Comment by motin** [comment]
Same here in 4.5.1 and 5.0.0. Tried debugging it and after about 40mins I gave up. Reverting to 4.3.0 fixes this, so this is a regression that occurred between 4.3.0 and 4.5.1 and has not been fixed in 5.0.0.

**Comment by grandmastermilo** [comment]
@motin im still getting the problem after reverting to 4.3.0. Any tips?

**Comment by felipe-najson-ntf** [comment]
@motin @federico-fiorini @grandmastermilo Hello everyone, the issue was resolved and merged to the repository. It will be available in the next release of the library that will be in these days.

Thanks for your contribution!
